Repository internxt/drive-web, pull requests merged in 2023-11, with the labels that each got.

#891 [PB-1080]: fix/folder name on task logger
  src/app/shared/components/Grid/GridItem.tsx
  src/app/tasks/services/tasks.service/index.ts
  test/e2e/cypress/plugins/index.ts
Labels: bug

#906 Fix rename button on top bar in drive explorer
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
Labels: bug

#914 [_]: chinese translations added by intfans
  src/app/i18n/locales/cn.json
Labels: enhancement

#912 [_]: feat/ga integration
  .env.example
  public/index.html
  src/app/analytics/services/analytics.service.ts
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/core/views/Preferences/tabs/Account/Usage.tsx
  src/react-app-env.d.ts
Labels: enhancement

#899 [PB-1063] feature/add web workers to upload
  CODEOWNERS
  babel.config.js
  package.json
  src/WebWorker.ts
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/services/stream.service.ts
  src/app/core/services/zipFolder.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/network.service/index.ts
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/network/upload.ts
  src/app/share/views/ShareView/SharePhotosView.tsx
  src/app/store/slices/photos/thunks/download.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/upload.worker.ts
  yarn.lock
Labels: enhancement

#918 [PB-702] : feature/Show parent folder in breadcrumb when accessing a folder URL directly
  package.json
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  yarn.lock
Labels: enhancement

#892 [PB-995] Feat/enable invite users public sharings
  package.json
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/share/components/ShareItemDialog/ShareItemDialog.tsx
  src/app/share/services/share.service.ts
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/storage.model.ts
  yarn.lock
Labels: enhancement

#920 [PB-1235]: bugfix/Refresh move dialog when create a folder
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
Labels: bug

#921 [PB-1235] bugfix/Put new created folder in move levels collection
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
Labels: bug

#923 [_]: Feature/Increase from 10GB to 20GB the upload file size limit
  .eslintrc.json
  .github/workflows/ci.yml
  CODEOWNERS
  babel.config.js
  craco.config.js
  package.json
  src/App.tsx
  src/WebWorker.ts
  src/app/analytics/services/analytics.service.ts
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/services/stream.service.ts
  src/app/core/services/zip.service.ts
  src/app/core/services/zipFolder.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/network.service/index.ts
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/network/upload.ts
  src/app/payment/components/token/PayForm.tsx
  src/app/share/views/ShareView/SharePhotosView.tsx
  src/app/shared/components/Dropdown/index.tsx
  src/app/store/slices/photos/thunks/download.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/services/tasks.service/index.ts
  src/app/utils/dnd-utils.ts
  src/assets/icons/app-store.svg
  src/assets/icons/play-store.svg
  src/index.tsx
  src/upload.worker.ts
  test/e2e/cypress/integration/change-password.spec.ts
  test/e2e/cypress/integration/download-file.spec.ts
  test/e2e/cypress/integration/download-folder.spec.ts
  test/e2e/cypress/integration/drag-and-drop.spec.ts
  test/e2e/cypress/integration/photos.spec.ts
  test/e2e/cypress/integration/recents-panel.spec.ts
  test/e2e/cypress/integration/remove-folder.spec.ts
  test/e2e/cypress/integration/rename-file.spec.ts
  test/e2e/cypress/integration/unauthorized.spec.ts
  yarn.lock
Labels: enhancement, dependencies

#922 [PB-1044]: feat/view item details
  package.json
  src/app/crypto/services/utils.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/drive/components/ItemDetailsDialog/components/ItemDetailsSkeleton.tsx
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/drive/views/RecentsView/RecentsView.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/store/slices/ui/index.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#927 [PB-1279]: feat/add dropdown in header
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Dropdown/index.tsx
  src/assets/icons/move.svg
Labels: enhancement

#939 [_]: fix/open preview in details dialog
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Dropdown/index.tsx
Labels: bug

#938 [_]: release
  package.json
  src/app/crypto/services/utils.ts
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/drive/components/ItemDetailsDialog/components/ItemDetailsSkeleton.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/drive/views/RecentsView/RecentsView.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Dropdown/index.tsx
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
  src/app/store/slices/ui/index.ts
  src/assets/icons/move.svg
  tailwind.config.js
  yarn.lock
Labels: bug, enhancement

#943 [PB-1278]: fix/remove duplicated edit name dialog
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
Labels: bug
