Repository internxt/drive-web, pull requests merged in 2023-01, with the labels that each got.

#556 bugfix/fix-deployment
  .npmrc
  package.json
Labels: bug

#560 [_] Bugfix/ Fix open internxt page when click to Try out Intnernxt button
  src/app/core/layouts/ShareLayout/ShareLayout.tsx
Labels: bug

#550 [WT-263] - Change way of reporting files and folders with same name uploaded
  package.json
  src/app/core/layouts/HeaderAndSidenavLayout/HeaderAndSidenavLayout.tsx
  src/app/drive/components/ClearTrashDialog/ClearTrashDialog.tsx
  src/app/drive/components/DeleteItemsDialog/DeleteItemsDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.scss
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemDragAndDrop.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/components/NameCollisionDialog/index.tsx
  src/app/i18n/locales/en.json
  src/app/photos/components/Preview.tsx
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/shared/components/BaseDialog/BaseDialog.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Button/Button.tsx
  src/app/shared/components/List/ListItem.tsx
  src/app/shared/components/List/index.tsx
  src/app/shared/components/Modal/index.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/renameItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/ui/index.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  yarn.lock
Labels: enhancement

#537 [_]: Chore/share domain
  .github/workflows/cd-to-share.yml
  infrastructure/share/share.Dockerfile
  infrastructure/share/share.env
  src/app/core/services/navigation.service.ts
Labels: stalled

#557 [WT-288] feature/Use the browser database to store photos and files content
  package.json
  src/app/core/config/app.json
  src/app/core/services/date.service.test.ts
  src/app/core/services/date.service.ts
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/services/database.service.ts
  yarn.lock
Labels: enhancement

#567 [WT-290 & WT-292] implement lru algorithm to store files content
  package.json
  src/App.tsx
  src/app/database/services/database.service/LRUCache.ts
  src/app/database/services/database.service/LRUFilesCacheManager.ts
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/database/services/database.service/mocks.ts
  src/app/database/services/database.service/utils.test.ts
  src/app/database/services/database.service/utils.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/NameCollisionDialog/index.tsx
  src/app/drive/services/database.service.test.ts
  src/app/drive/services/database.service.ts
  src/app/store/slices/photos/thunks/delete.ts
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/use_cases/trash/delete-items.ts
  src/use_cases/trash/move-items-to-trash.ts
  yarn.lock
Labels: enhancement

#568 [WT-287] Feature/client side caching
  package.json
  src/App.tsx
  src/app/core/config/app.json
  src/app/core/services/date.service.test.ts
  src/app/core/services/date.service.ts
  src/app/database/services/database.service/LRUCache.ts
  src/app/database/services/database.service/LRUFilesCacheManager.ts
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/database/services/database.service/mocks.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/NameCollisionDialog/index.tsx
  src/app/drive/services/database.service.test.ts
  src/app/drive/services/database.service.ts
  src/app/store/slices/photos/thunks/delete.ts
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/use_cases/trash/delete-items.ts
  src/use_cases/trash/move-items-to-trash.ts
  yarn.lock
Labels: enhancement

#559 [WT-275]: feat/add options to current breadcrumb
  cypress-transform-dotenv.js
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemDragAndDrop.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveStoreProps.tsx
  src/app/drive/components/EditFolderNameDialog/EditFolderNameDialog.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/types/index.ts
  src/app/photos/components/PhotoThumbnail.tsx
  src/app/photos/components/Toolbar.tsx
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Dropdown/index.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/ui/index.ts
  src/index.scss
  src/use_cases/trash/recover-items-from-trash.ts
  tailwind.config.js
  test/e2e/cypress/integration/photos.spec.ts
  test/e2e/cypress/utils/photos.mock.ts
Labels: enhancement

#569 [WT-317] feature/Added profile photo to cache
  src/app/core/components/Navbar/AccountPopover.tsx
  src/app/core/config/app.json
  src/app/core/services/date.service.ts
  src/app/core/views/Preferences/tabs/Account/AvatarWrapper.tsx
  src/app/core/views/Preferences/tabs/Account/UserHeader.tsx
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/drive/components/EditFolderNameDialog/EditFolderNameDialog.tsx
  src/app/drive/services/database.service.ts
  src/app/store/slices/user/index.ts
Labels: enhancement

#573 [_] bugfix/ Added file source blob to updateDatabaseFileSourceData function
  src/app/drive/services/database.service.ts
Labels: enhancement
