Repository internxt/drive-web, pull requests merged in 2023-12, with the labels that each got.

#947 [PB-1351] bugfix/Manage Access option isn't working in a folder inside a shared folder
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
Labels: bug

#934 [PB-968]: fix/rename item in preview view
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerGridItem/DriveExplorerGridItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/components/TopBarActions.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/drive/services/database.service.ts
  src/app/drive/types/index.ts
  src/app/network/download.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
Labels: bug

#944 [PB-1348]: fix/hide list header
  src/app/shared/components/List/index.tsx
  src/assets/icons/move.svg
Labels: bug

#953 [_]: feat/add Spanish translation for signup blog banner
  src/app/auth/views/Auth/SignupBlog.tsx
Labels: enhancement

#950 [PB-1361]: bugfix/Fixed copy link when document not focused
  src/app/share/services/share.service.ts
Labels: bug

#924 [PB-1267] - feature/No Private access view
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/services/auth.service.ts
  src/app/core/config/views.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/views/RequestAccess/RequestAccess.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
Labels: enhancement

#928 [PB-1130] Share Dialog General Access closes itself
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveTopBarItems.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
Labels: bug

#930 [PB-1129] bugfix/Global Search filters are not responsive to small screens
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
Labels: bug

#955 [_]: feature/Update chinese translations
  src/app/i18n/locales/cn.json
Labels: enhancement

#957 [PB-1422] bugfix/Cannot upload a folder into shared folder
  package.json
  src/app/banners/BannerWrapper.tsx
  src/app/banners/BlackFridayBanner.tsx
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/assets/images/banner/christmas_banner_bg.png
Labels: bug

#952 [PB-1367]: feat/update Empty state inside the folders
  src/app/share/components/EmptySharedView/EmptySharedView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
Labels: enhancement

#956 [PB-1372]: fix/user can't rename an item by pressing "R" in preview mode.
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
Labels: bug

#965 [_] feature/Added data ids for cypress in login
  src/app/auth/components/Button/Button.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/PasswordInput/PasswordInput.tsx
  src/app/auth/components/TextInput/TextInput.tsx
Labels: enhancement

#967 [_]_ Release/staging release
  package.json
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/user.service.ts
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerGridItem/DriveExplorerGridItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/components/TopBarActions.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/components/ShareUserNotRegistered/ShareUserNotRegistered.tsx
  src/app/drive/services/database.service.ts
  src/app/drive/types/index.ts
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/network/download.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/List/index.tsx
  src/app/shared/views/ExpiredLink/ExpiredLinkView.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/assets/icons/move.svg
  yarn.lock
Labels: bug, enhancement

#954 [PB-1373]: Fix/User can't send item to trash in preview mode in Shared
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/StopSharingItemDialog/StopSharingItemDialog.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/ui/index.ts
Labels: bug

#959 [PB-1210]: fix/context menu options aren't completely displayed
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/shared/components/List/ListItem.tsx
Labels: bug

#962 [PB-1423]: fix/restore items from trash
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
Labels: bug

#969 [PB-1447] feature/breadcrumbs error on shared view
  package.json
  src/app/auth/components/Button/Button.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/PasswordInput/PasswordInput.tsx
  src/app/auth/components/TextInput/TextInput.tsx
  src/app/auth/views/Auth/SignupBlog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
Labels: bug

#971 [PB-1447,PB-1422] bugfix/breadcrumbs error on shared view
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
Labels: bug

#926 [PB-472]: feat/navigate files and folders with url
  src/App.tsx
  src/app/analytics/services/analytics.service.ts
  src/app/auth/views/Auth/signup.ts
  src/app/auth/views/RecoverView/RecoverView.tsx
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/layouts/ShareLayout/ShareLayout.tsx
  src/app/core/services/navigation.service.ts
  src/app/core/types.ts
  src/app/core/views/Preferences/index.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveGridItemSkeleton/DriveGridItemSkeleton.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/services/file.service/index.ts
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/drive/views/FolderFileNotFound/FolderFileNotFound.tsx
  src/app/drive/views/RecentsView/RecentsView.tsx
  src/app/drive/views/TrashView/TrashView.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/photos/views/PhotosView.tsx
  src/app/share/types/index.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Dropdown/index.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  test/e2e/cypress/integration/backups.spec.ts
  test/e2e/cypress/integration/change-password.spec.ts
  test/e2e/cypress/integration/photos.spec.ts
  test/e2e/cypress/integration/recents-panel.spec.ts
  test/e2e/cypress/integration/signup-password-requirements.spec.ts
  test/e2e/cypress/integration/signup.spec.ts
  test/e2e/cypress/support/commands.ts
Labels: enhancement

#972 [_]: feature/Add test ids in drive view
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/SidenavItem/SidenavItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveTopBarItems.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Button/Button.tsx
  src/app/shared/components/List/index.tsx
  src/app/shared/components/forms/BaseCheckbox/BaseCheckbox.tsx
Labels: enhancement
