Repository internxt/drive-web, pull requests merged in 2023-07, with the labels that each got.

#729 [_]: bugfix/Hide search bar in backups and shared links views
  src/app/core/config/app.json
Labels: bug

#738 [PB-119] feature/Rotate drive sharing file drive subdomain
  package.json
  src/App.tsx
  src/app/share/components/ShareItemDialog/ShareItemDialog.tsx
  src/app/share/services/DomainManager.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  yarn.lock
Labels: enhancement

#721 PB-118 Advanced sharing
  .github/workflows/ci.yml
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/layouts/HeaderAndSidenavLayout/HeaderAndSidenavLayout.tsx
  src/app/core/services/env.service.ts
  src/app/core/types.ts
  src/app/core/views/Preferences/tabs/Account/AccountDetails.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
  src/app/drive/components/FileViewer/components/TopBarActions.tsx
  src/app/drive/components/ShareDialog/ShareDialog.scss
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.scss
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/views/RequestAccess/RequestAccess.scss
  src/app/drive/views/RequestAccess/RequestAccess.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/notifications/components/NotificationToast/NotificationToast.tsx
  src/app/share/services/DomainManager.ts
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/shared/components/Button/Button.tsx
  src/app/shared/components/DefaultAvatar/index.tsx
  src/app/shared/components/List/ListItem.tsx
  src/app/shared/components/List/index.tsx
  src/app/shared/components/Modal/index.tsx
  src/app/shared/components/PictureAvatar/index.tsx
  src/app/shared/components/Tooltip/Tooltip.tsx
  src/app/store/slices/ui/index.ts
  src/react-app-env.d.ts
  tailwind.config.js
Labels: enhancement

#740 [PB-713]: feat/preview-audio
  src/App.tsx
  src/app/core/services/media.service.ts
  src/app/core/services/stream.service.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/viewers/FileAudioViewer/FileAudioViewer.tsx
  src/app/drive/components/FileViewer/viewers/FilePdfViewer/FilePdfViewer.tsx
  src/app/drive/components/FileViewer/viewers/FileVideoViewer/FileVideoViewer.tsx
  src/app/drive/components/FileViewer/viewers/index.tsx
  src/app/drive/services/database.service.ts
  src/app/drive/types/file-types.ts
  src/app/network/download/v2.ts
Labels: enhancement

#728 [PB-690] feature/Add required metadata
  src/app/analytics/TrackingPlan.ts
  src/app/analytics/services/analytics.service.ts
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/folder.service.ts
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
Labels: enhancement

#748 []: bugfix/file viewer bug
  src/app/drive/components/FileViewer/FileViewer.tsx
Labels: bug

#749 [PB-735] feature/Add e2e test to check icons of drive list
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/assets/icons/file-types/audio.svg
  src/assets/icons/file-types/image.svg
  src/assets/icons/file-types/pdf.svg
  src/assets/icons/file-types/video.svg
  src/assets/icons/file-types/zip.svg
  src/assets/icons/light/folder.svg
  test/e2e/cypress.json
  test/e2e/cypress/constans.ts
  test/e2e/cypress/fixtures/test-user.json
  test/e2e/cypress/integration/drive-icon-list.spec.ts
  test/e2e/cypress/utils/drive.mock.ts
Labels: enhancement

#751 [PB-696] feature/Allow users to recover password from backup key
  package.json
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/ForgotPassword/ForgotPassword.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/RecoveryLink/RecoveryLink.tsx
  src/app/auth/components/RestartAccount/RestartAccount.tsx
  src/app/auth/services/auth.service.ts
  src/app/auth/views/RecoverAccountView/RecoverAccountView.tsx
  src/app/auth/views/RecoveryLinkView/RecoveryLinkView.tsx
  src/app/auth/views/RemoveAccountView/RemoveAccountView.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/index.scss
  yarn.lock
Labels: enhancement

#715 [PB-206] feature/Folder refresh after an upload
  src/App.tsx
  src/app/core/services/socket.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/store/slices/user/index.ts
Labels: enhancement

#665 [_]: feature/Added onboarding test end to end and fix files plain name display
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/shared/components/Tutorial/OnBoardingModal.tsx
  test/e2e/cypress.json
  test/e2e/cypress/integration/signup-onboarding.spec.ts
  test/e2e/cypress/support/commands.ts
  test/e2e/cypress/support/index.d.ts
Labels: enhancement, stalled

#758 [PB-752]: fix/private-key-decryption-failure-on-login
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/services/auth.service.ts
  src/app/crypto/services/keys.service.ts
Labels: bug
