Repository internxt/drive-web, pull requests merged in 2024-02, with the labels that each got.

#995 [PB-1536, PB-1537, PB-1538, PB-1539] Added files and folders pause upload ability and retry file upload
  src/WebWorker.ts
  src/app/core/config/app.json
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/network.service/index.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/drive/services/worker.service/uploadWorkerUtils.ts
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/network/upload.ts
  src/app/repositories/DatabaseUploadRepository.ts
  src/app/store/slices/storage/hooks/useReduxActions.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useRetry.ts
  src/app/tasks/hooks/useRetryDownload.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
Labels: enhancement

#1012 [_] feature/Add data cy to edit item name dialog and drive list items
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/shared/components/Button/Button.tsx
  src/app/shared/components/Input/index.tsx
  src/app/shared/components/List/ListItem.tsx
  src/app/shared/components/List/index.tsx
Labels: enhancement

#1001 [PB-1569] feature/Add open file/folder from success upload
  src/App.tsx
  src/app/i18n/locales/cn.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/storage.thunks/createFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useOpen.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  src/hooks/useBeforeUnload.ts
Labels: enhancement

#1015 [_] feat/remove data privacy banner
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
Labels: enhancement

#1014 [PB-1285]: feature/Manage upload
  src/App.tsx
  src/WebWorker.ts
  src/app/analytics/TrackingPlan.ts
  src/app/analytics/services/analytics.service.ts
  src/app/core/config/app.json
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/network.service/index.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/drive/services/worker.service/uploadWorkerUtils.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/network/upload.ts
  src/app/repositories/DatabaseUploadRepository.ts
  src/app/store/slices/storage/hooks/useReduxActions.ts
  src/app/store/slices/storage/storage.thunks/createFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerButton/TaskLoggerButton.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/index.tsx
  src/app/tasks/hooks/useOpen.tsx
  src/app/tasks/hooks/useRetry.ts
  src/app/tasks/hooks/useRetryDownload.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  src/assets/icons/tasklogger/circle-arrow.svg
  src/assets/icons/tasklogger/cross.svg
  src/assets/icons/tasklogger/download-icon.svg
  src/assets/icons/tasklogger/error.svg
  src/assets/icons/tasklogger/magnifying-glass.svg
  src/assets/icons/tasklogger/pause.svg
  src/assets/icons/tasklogger/paused-icon.svg
  src/assets/icons/tasklogger/play.svg
  src/assets/icons/tasklogger/success-check.svg
  src/assets/icons/tasklogger/upload-icon.svg
  src/hooks/useBeforeUnload.ts
Labels: enhancement

#1017 [PB-1285]: feature/Manage upload
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/hooks/useReduxActions.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useRetry.ts
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
Labels: enhancement

#1002 [PB-1523] bugfix/Rename dialog not shows current name item
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
Labels: bug

#1019 [PB-1649] bugfix/Hide temporary new roles
  src/app/drive/components/ShareDialog/ShareDialog.tsx
Labels: bug

#1018 [_] release/Staging
  .env.example
  .vscode/settings.json
  package.json
  src/App.tsx
  src/app/analytics/TrackingPlan.ts
  src/app/analytics/services/analytics.service.ts
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/ResendButton/ResendButton.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/services/auth.service.ts
  src/app/auth/views/BlockedAccountView/BlockedAccountView.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/core/views/Preferences/tabs/Account/index.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/utils/fileViewerWrapperUtils.ts
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/StopSharingAndMoveToTrashDialogWrapper.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/components/StopSharingAndMoveToTrashDialog/index.tsx
  src/app/drive/components/StopSharingItemDialog/StopSharingItemDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/index.ts
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/i18n/services/i18n.service.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/List/ListItem.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/ui/index.ts
  yarn.lock
Labels: bug, enhancement

#1022 [MKT-253]: feat/add banner for lifetime soft sale
  src/app/banners/Banner.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement

#1025 [MKT-254]: feat/valentines banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement

#1003 [PB-1524]: feat/allow the user to download the backup key when registering
  src/app/auth/components/Button/Button.scss
  src/app/auth/components/Button/Button.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/views/Auth/AuthView.tsx
  src/app/auth/views/DownloadBackupKey/DownloadBackupKey.tsx
  src/app/core/views/Preferences/tabs/Security/BackupKey.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/share/components/EmptySharedView/EmptySharedView.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/shared/views/ExpiredLink/ExpiredLinkView.tsx
Labels: enhancement

#1026 [_]: fix/remove download key step
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
Labels: enhancement

#1029 [BR-156] bugfix/After uploading a file, the message "Let's get started...upload a file..." continues to appear
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/core/services/local-storage.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
Labels: bug

#1030 [BR-156] bugfix/After uploading a file, the message "Let's get started...upload a file..." continues to appear
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/core/services/local-storage.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
Labels: bug

#1031 [PB-1664] bugfix/ Upload continues transfering data even after pausing it.
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/types.ts
Labels: bug, enhancement

#1034 [PB-1699]: bugfix/ New navigation fetches the entire contents of the folder
  package.json
  src/app/core/components/Navbar/Navbar.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/index.ts
Labels: bug

#1028 [PB-1639] refactor/Refactor Shared view component
  .gitignore
  src/app/core/config/views.ts
  src/app/crypto/services/utils.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/StopSharingAndMoveToTrashDialogWrapper.tsx
  src/app/share/services/redirections.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/SharedViewWrapper.tsx
  src/app/share/views/SharedLinksView/components/SharedItemList.tsx
  src/app/share/views/SharedLinksView/components/TopBarButtons.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/share/views/SharedLinksView/context/SharedViewContext.actions.ts
  src/app/share/views/SharedLinksView/context/SharedViewContext.ts
  src/app/share/views/SharedLinksView/context/SharedViewContextProvider.tsx
  src/app/share/views/SharedLinksView/hooks/useFetchSharedData.tsx
  src/app/share/views/SharedLinksView/hooks/useSharedContextMenu.ts
  src/app/share/views/SharedLinksView/sharedViewUtils.ts
  src/app/shared/components/List/index.tsx
  src/app/utils/driveItemsUtils.test.ts
  src/app/utils/driveItemsUtils.ts
Labels: enhancement

#1041 [_]: feat/add lifetime soft banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement

#1043 [_]: feature/Added control of pause button and pause progress
  src/app/network/UploadManager.ts
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
Labels: enhancement

#1045 [_]: bugfix/Fixed behaviour that cancel all uploads if one is cancelled
  src/app/network/UploadManager.ts
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useRetry.ts
Labels: bug, enhancement

#1038 [PB-1640]: feature/Refactor new navigation in Drive
  src/App.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/services/config.service.ts
  src/app/core/services/navigation.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/routes/Share/ShareRedirection.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  src/app/routes/paths.json
  src/app/routes/routes.tsx
Labels: enhancement
