Repository internxt/drive-web, pull requests merged in 2024-04, with the labels that each got.

#1069 [MKT-227]: feat/add world cloud security banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1070 [_]: feature/master to staging
  .github/workflows/build-and-publish-preview.yaml
  .github/workflows/clean-up-pr-preview.yaml
  .github/workflows/deploy-pr-preview.yaml
  .github/workflows/slash-command-dispatcher.yaml
  infrastructure/preview.Dockerfile
  package.json
  src/app/auth/views/RecoveryLinkView/RecoveryLinkView.tsx
  src/app/auth/views/SignInView/SignInView.tsx
  src/app/auth/views/SignUpView/SignUpView.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/i18n/provider/TranslationProvider.tsx
  src/app/network/UploadManager.ts
  src/app/shared/components/Tutorial/signUpSteps.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/storage/storage.selectors.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchSortedFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/react-app-env.d.ts
Labels: enhancement, ready-for-preview

#1074 [PB-1826]:/Fix upload button overlap
  src/app/share/views/SharedLinksView/SharedView.tsx
Labels: enhancement, ready-for-preview

#1071 [PB-1948] bugfix/downloading zip error for staging
  src/app/core/collections.ts
  src/app/drive/services/filesZip.service.test.ts
  src/app/drive/services/filesZip.service.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/foldersZip.service.test.ts
  src/app/drive/services/foldersZip.service.ts
Labels: bug, ready-for-preview

#1073 [MKT-278]: feat/add identity management day banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1075 Added members section and created basic components
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/components/PreferencesDialog.tsx
  src/app/newSettings/types.tsx
  src/app/newSettings/views/MembersSection.tsx
Labels: enhancement

#993 [PB-1526]: feat/details actions in Grid view
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerGridItem/DriveExplorerGridItem.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/network/UploadManager.ts
  src/app/share/components/EmptySharedView/EmptySharedView.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/react-app-env.d.ts
  src/use_cases/trash/recover-items-from-trash.ts
Labels: bug, ready-for-preview

#1078 [PB-1989] feature/Create member details view
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Workspace/Members/Components/RoleBadge.tsx
  src/app/newSettings/Workspace/Members/Components/UserCard.tsx
  src/app/newSettings/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/newSettings/components/Usage/UsageBar.tsx
  src/app/newSettings/views/MembersSection.tsx
Labels: enhancement, ready-for-preview

#1079 [MKT-290]: feat/update identity management banner
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1080 [PB1992] feature/create deactivate member modal
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Workspace/Members/Components/ActionModal.tsx
  src/app/newSettings/Workspace/Members/Components/DeactivateModal.tsx
  src/app/newSettings/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/shared/components/Modal/index.tsx
Labels: enhancement, ready-for-preview

#1082 [PB-1993] feature/Add request change password modal
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Account/Account/components/TextArea.tsx
  src/app/newSettings/Workspace/Members/Components/ActionModal.tsx
  src/app/newSettings/Workspace/Members/Components/RequestPasswordModal.tsx
  src/app/newSettings/Workspace/Members/Components/UserCard.tsx
  src/app/newSettings/Workspace/Members/containers/MemberDetailsContainer.tsx
Labels: enhancement

#1085 [PB-1638]: bugfix/Modify close behaviour of file preview in backups
  src/App.tsx
Labels: bug, enhancement, ready-for-preview

#1086 [PB-1638]: bugfix/fix display breadcrumbs menu in backups view
  src/app/i18n/locales/es.json
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
Labels: ready-for-preview

#1089 [PB-1948] bugfix/Downloading zip error
  src/app/core/collections.ts
  src/app/drive/services/filesZip.service.test.ts
  src/app/drive/services/filesZip.service.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/foldersZip.service.test.ts
  src/app/drive/services/foldersZip.service.ts
Labels: bug, ready-for-preview

#1087 [PB-2028] feature/Create plan card component
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
Labels: enhancement

#1083 [MKT-300]: feat/add file converter banner
  src/app/banners/Banner.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/assets/images/banner/file-converter-banner.webp
Labels: enhancement, ready-for-preview

#1091 [_]: feat/Add prevention value for usage when photos endpoint is deleted
  src/app/drive/services/usage.service.ts
  src/app/photos/components/Preview.tsx
  src/app/photos/components/Toolbar.tsx
Labels: enhancement, ready-for-preview

#1090 [PB-2029,PB-2030,PB-2031]: feature/ add plan selector
  src/app/core/views/Preferences/tabs/Plans/PlanSelector.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/api.ts
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/TabButton.tsx
  src/app/newSettings/Sections/Account/Plans/planUtils.ts
Labels: enhancement

#1093 [MKT-304]: feat/add lifetime banner
  src/app/banners/Banner.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1092 [_] release/staging
  .gitignore
  src/App.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/services/config.service.ts
  src/app/core/services/navigation.service.ts
  src/app/crypto/services/utils.ts
  src/app/drive/components/DeleteBackupDialog/DeleteBackupDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/StopSharingAndMoveToTrashDialogWrapper.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/i18n/locales/es.json
  src/app/routes/Share/ShareRedirection.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  src/app/routes/paths.json
  src/app/routes/routes.tsx
  src/app/share/services/redirections.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/SharedViewWrapper.tsx
  src/app/share/views/SharedLinksView/components/SharedItemList.tsx
  src/app/share/views/SharedLinksView/components/TopBarButtons.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/share/views/SharedLinksView/context/SharedViewContext.actions.ts
  src/app/share/views/SharedLinksView/context/SharedViewContext.ts
  src/app/share/views/SharedLinksView/context/SharedViewContextProvider.tsx
  src/app/share/views/SharedLinksView/hooks/useFetchSharedData.tsx
  src/app/share/views/SharedLinksView/hooks/useSharedContextMenu.ts
  src/app/share/views/SharedLinksView/sharedViewUtils.ts
  src/app/shareLinks/services/shared.service.ts
  src/app/shareLinks/types.ts
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsMoveItemsDialogView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsSharedView.tsx
  src/app/shared/components/Breadcrumbs/types.tsx
  src/app/shared/components/List/index.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/utils/driveItemsUtils.test.ts
  src/app/utils/driveItemsUtils.ts
Labels: bug, enhancement, ready-for-preview

#1094 [_] feature/Reorganize new preferences files
  src/app/core/services/navigation.service.ts
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Account/AccountSection.tsx
  src/app/newSettings/Sections/Account/Account/containers/AccountUsageContainer.tsx
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Account/Billing/components/CancelSubscription.tsx
  src/app/newSettings/Sections/Account/Billing/containers/BillingAccountOverview.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/api/plansApi.ts
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/newSettings/Sections/Account/Security/SecuritySection.tsx
  src/app/newSettings/Sections/Account/Security/components/ChangePassword.tsx
  src/app/newSettings/Sections/Account/Security/components/ChangePasswordModal.tsx
  src/app/newSettings/Sections/Account/Security/components/EnterPassword.tsx
  src/app/newSettings/Sections/Account/Security/components/ExportBackupKey.tsx
  src/app/newSettings/Sections/Account/Security/components/FrecuentlyAskedQuestions.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthentication.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationDisableModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationEnableModal.tsx
  src/app/newSettings/Sections/General/GeneralSection.tsx
  src/app/newSettings/Sections/General/components/ContactSupport.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingDetailsCard.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/Detail.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/containers/BillingWorkspaceOverview.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ActivityTab.tsx
  src/app/newSettings/Sections/Workspace/Members/components/RoleBadge.tsx
  src/app/newSettings/Sections/Workspace/Members/components/TeamsTab.tsx
  src/app/newSettings/Sections/Workspace/Members/components/UserCard.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/components/Tabs.tsx
  src/app/newSettings/components/Usage/UsageBar.tsx
  src/app/newSettings/containers/UsageContainer.tsx
  src/app/newSettings/types/types.tsx
  src/app/newSettings/utils/suscriptionUtils.ts
Labels: enhancement

#1097 [_]: Reset loader when click on folder to navigate
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/index.ts
Labels: enhancement, ready-for-preview

#1099 Revert "Revert "[_] release/staging""
  .gitignore
  src/App.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/config/app.json
  src/app/core/config/views.ts
  src/app/core/services/config.service.ts
  src/app/core/services/navigation.service.ts
  src/app/crypto/services/utils.ts
  src/app/drive/components/DeleteBackupDialog/DeleteBackupDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/DriveItemDropdownActions/DriveItemDropdownActions.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/StopSharingAndMoveToTrashDialogWrapper.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/i18n/locales/es.json
  src/app/routes/Share/ShareRedirection.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  src/app/routes/paths.json
  src/app/routes/routes.tsx
  src/app/share/services/redirections.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/share/views/SharedLinksView/SharedLinksView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/SharedViewWrapper.tsx
  src/app/share/views/SharedLinksView/components/SharedItemList.tsx
  src/app/share/views/SharedLinksView/components/TopBarButtons.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/share/views/SharedLinksView/context/SharedViewContext.actions.ts
  src/app/share/views/SharedLinksView/context/SharedViewContext.ts
  src/app/share/views/SharedLinksView/context/SharedViewContextProvider.tsx
  src/app/share/views/SharedLinksView/hooks/useFetchSharedData.tsx
  src/app/share/views/SharedLinksView/hooks/useSharedContextMenu.ts
  src/app/share/views/SharedLinksView/sharedViewUtils.ts
  src/app/shareLinks/services/shared.service.ts
  src/app/shareLinks/types.ts
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsMoveItemsDialogView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsSharedView.tsx
  src/app/shared/components/Breadcrumbs/types.tsx
  src/app/shared/components/List/index.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/utils/driveItemsUtils.test.ts
  src/app/utils/driveItemsUtils.ts
Labels: enhancement, ready-for-preview

#1102 [PB-2061] bugfix/Remove drive explorer loader
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/shared/components/List/index.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchSortedFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/index.ts
Labels: bug, enhancement, ready-for-preview

#1100 [_]: release/Staging
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/shared/components/List/index.tsx
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchSortedFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/index.ts
Labels: enhancement, ready-for-preview

#1103 [PB-2059] bugfix/Thumbnails are not regenerated in Drive
  package.json
  src/app/banners/Banner.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/utils/fileViewerWrapperUtils.ts
  src/app/drive/services/database.service.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/drive/services/usage.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/photos/components/Preview.tsx
  src/app/photos/components/Toolbar.tsx
  src/app/store/slices/storage/index.ts
  src/assets/images/banner/file-converter-banner.webp
Labels: bug, enhancement, ready-for-preview

#1104 [PB-2059] bugfix/Restore arrow functionality in preview mode
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/services/database.service.ts
Labels: bug, ready-for-preview

#1105 [PB-1958] feature/Remove the Photos Web Gallery
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/config/views.ts
Labels: enhancement, ready-for-preview

#1107 [MKT-313]: feat/update Sign Up blog image
  src/app/auth/views/Auth/SignupBlog.tsx
  src/assets/images/banner/Internxt-secure-cloud-storage.webp
  src/assets/images/banner/internxt_secure_cloud_storage.webp
Labels: enhancement, ready-for-preview
