Repository internxt/drive-web, pull requests merged in 2024-11, with the labels that each got.

#1335 [PB-2301] feat/sharing content between teams
  src/app/drive/components/ShareWithTeamDialog/ShareWithTeamDialog.tsx
Labels: ready-for-preview

#1339 [_]: fix/removing duplicated features
  src/app/i18n/locales/en.json
Labels: bug, ready-for-preview

#1340 [PB-3263]: fix/workspace invitation date
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
Labels: ready-for-preview

#1342 [_]: fix/wrongLogin key and value for login error
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: bug, ready-for-preview

#1344 [PB-3283]: fix/error while uploading avatar image
  src/app/auth/services/user.service.ts
  src/app/core/factory/sdk/index.ts
Labels: bug, ready-for-preview

#1337 [PB-2173]: fix/invoice table style
  src/app/newSettings/components/Invoices/InvoicesList.tsx
Labels: bug, ready-for-preview

#1338 [_]: fix/sonar issues
  src/App.tsx
  src/app/analytics/impact.service.ts
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/components/TextInput/TextInput.tsx
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/auth/views/Auth/AuthView.tsx
  src/app/auth/views/UnivesalLinkSuccessView/UniversalLinkSuccessView.tsx
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersListItem.tsx
  src/app/backups/components/DeviceList/DeviceList.tsx
  src/app/backups/components/DeviceList/DeviceListItem.tsx
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/core/components/Navbar/FilterItem.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/SidenavItem/SidenavItem.tsx
  src/app/core/services/drag-and-drop.service.ts
  src/app/core/services/media.service.ts
  src/app/core/views/ChangeEmailView/index.tsx
  src/app/core/views/NotFoundView/NotFoundView.tsx
  src/app/core/views/VerifyEmailView/index.tsx
  src/app/database/services/database.service/LRUCache.ts
  src/app/database/services/database.service/index.ts
  src/app/drive/components/DeleteBackupDialog/DeleteBackupDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/components/NameCollisionDialog/index.tsx
  src/app/drive/hooks/trash/useTrashPagination.test.ts
  src/app/drive/hooks/trash/useTrashPagination.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/folder.service/uploadFolderInput.service.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.model.ts
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/renameItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/types.ts
  test/unit/services/keys.service.test.ts
Labels: enhancement, ready-for-preview

#1345 [_]: fix/change password endpoint
  src/app/auth/services/auth.service.ts
Labels: bug, ready-for-preview

#1348 [_]: feat/project coverage using sonarcloud
  .github/workflows/sonar-analysis.yml
  package.json
  sonar-project.properties
  src/app/drive/services/download.service/downloadBackup.ts
  src/app/drive/services/download.service/downloader.ts
  vitest.config.js
  yarn.lock
Labels: enhancement, ready-for-preview

#1347 [MKT-472]: Updating Features Banner
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.module.scss
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: ready-for-preview

#1349 [_]: fix/sonarcloud analysis
  .github/workflows/sonar-analysis.yml
  sonar-project.properties
  vitest.config.js
Labels: bug, ready-for-preview

#1350 [_]: fix/scroll for edit payment dialog
  src/app/newSettings/Sections/Workspace/Billing/components/EditPaymentMethodForm.tsx
Labels: bug, ready-for-preview

#1352 [PB-3292] fix/navigation back and forth
  src/App.tsx
  src/app/core/services/navigation.service.ts
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
Labels: ready-for-preview

#1317 Feat/PB-3080 generate pq keys for current users
  package.json
  patches/@internxt+sdk+1.5.17.patch
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/crypto/services/pgp.service.ts
  src/app/crypto/services/utils.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/network/crypto.ts
  src/app/network/download/v2.ts
  src/app/network/requests.ts
  src/app/network/upload.ts
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  src/app/share/services/share.service.ts
  src/app/share/types/index.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/share/views/SharedLinksView/context/SharedViewContext.ts
  src/app/share/views/SharedLinksView/context/SharedViewContextProvider.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  src/index.scss
  test/unit/services/pgp.service.test.ts
  test/unit/services/utils.test.ts
  tsconfig.json
  vitest.config.js
  yarn.lock
Labels: ready-for-preview

#1351 [_]: feat/notifying the user if something fails while accepting a workspace invitation
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1354 [_]: fix/download desktop app from sidenav
  src/app/core/components/Sidenav/Sidenav.tsx
Labels: bug, ready-for-preview

#1355 [PB-3313]: feat/update workspace members
  package.json
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/i18n/provider/TranslationProvider.tsx
  src/app/i18n/types.ts
  src/app/newSettings/Sections/Workspace/Billing/BillingDetailsCard.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/UpdateMembersCard.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/ConfirmUpdatedMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/SelectNewMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/containers/BillingWorkspaceOverview.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/components/DetailsInput.tsx
  src/app/newSettings/utils/suscriptionUtils.ts
  src/app/payment/services/payment.service.ts
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1368 [_] bugfix/Hide error message
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
Labels: bug, ready-for-preview

#1371 [PB-3401] switch to hmac from hash-wasm
  src/app/crypto/services/crypto.md
  src/app/crypto/services/utils.ts
  src/app/network/crypto.test.ts
  src/app/network/crypto.ts
  src/app/network/requests.ts
  test/unit/services/utils.hmac.test.ts
  yarn.lock
Labels: ready-for-preview

#1374 [_]: feature/Add pull request template
  .github/pull_request_template.md
Labels: enhancement, ready-for-preview
