Repository internxt/drive-web, pull requests merged in 2024-03, with the labels that each got.

#1050 [MKT-264]: feat/adding spring banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/i18n/provider/TranslationProvider.tsx
Labels: enhancement

#1049 [_]: feature/Improve update items thunk code
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
Labels: enhancement

#1053 [PB-1811] feature/Create Settings dialog navigation elements
  src/App.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/components/PreferencesDialog.tsx
  src/app/newSettings/components/SectionItem.tsx
  src/app/newSettings/components/SectionList.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/newSettings/types.tsx
  tailwind.config.js
Labels: enhancement

#1057 [PB-1862]: feature/Create workspace selector component
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
Labels: enhancement

#1061 [_]: fix/Auth View
  src/app/auth/views/RecoveryLinkView/RecoveryLinkView.tsx
  src/app/auth/views/SignInView/SignInView.tsx
  src/app/auth/views/SignUpView/SignUpView.tsx
Labels: bug

#1060 [_]: feat/dynamic-upload-concurrency-depending-on-ram-chrome
  src/app/network/UploadManager.ts
  src/react-app-env.d.ts
Labels: bug

#1046 [IN-31] ci: add needed actions
  .github/workflows/build-and-publish-preview.yaml
  .github/workflows/clean-up-pr-preview.yaml
  .github/workflows/deploy-pr-preview.yaml
  .github/workflows/slash-command-dispatcher.yaml
  infrastructure/preview.Dockerfile
Labels: preview, ready-for-preview

#1063 [PB-1897] fetature/Profile details section
  src/app/core/views/Preferences/tabs/Account/AccountDetails.tsx
  src/app/core/views/Preferences/tabs/Account/UserHeader.tsx
  src/app/core/views/Preferences/tabs/Account/index.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Account/Account/components/AccountDetailsModal.tsx
  src/app/newSettings/Account/Account/components/ChangeEmailModal.tsx
  src/app/newSettings/Account/Account/components/EmailMessageCard.tsx
  src/app/newSettings/Account/Account/components/UploadAvatarModal.tsx
  src/app/newSettings/Account/Account/components/UserHeader.tsx
  src/app/newSettings/Account/Account/containers/UserHeaderContainer.tsx
  src/app/newSettings/components/PreferencesDialog.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/newSettings/views/AccountSection.tsx
Labels: enhancement

#1066 Added invitate a friend UI and functionality
  src/app/core/views/Preferences/components/Section.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Account/Account/containers/InviteFriendSectionContainer.tsx
  src/app/newSettings/Account/Account/containers/InvitedFriendsContainer.tsx
  src/app/newSettings/components/VerticalDivider.tsx
  src/app/newSettings/hooks/useInviteFriends.ts
  src/app/newSettings/views/AccountSection.tsx
  src/app/shared/components/Input/index.tsx
Labels: enhancement
