Repository internxt/drive-web, pull requests merged in 2024-10, with the labels that each got.

#1289 [PB-2980]: fix/show item name in rename item dialog in Recents view
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/store/slices/storage/storage.thunks/fetchRecentsThunk.ts
Labels: bug, ready-for-preview

#1287 [PB-2990]: fix/drive button of the navigation sidebar when navigating through folders
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/SidenavItem/SidenavItem.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  yarn.lock
Labels: bug, ready-for-preview

#1276 [PB-2262]: fix/design workspace issues
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/UserCard.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/TeamDetails.tsx
  src/app/newSettings/components/Invoices/InvoicesList.tsx
Labels: bug, enhancement, ready-for-preview

#1295 [_]: feat/update Share with team label to Share with workspace
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1282 [PB-2375] bugfix/Check duplicated items before uploading on Drive web
  package.json
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemDragAndDrop.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/services/file.service/types.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/store/slices/storage/fileUtils/checkDuplicatedFiles.ts
  src/app/store/slices/storage/fileUtils/getUniqueFileName.test.ts
  src/app/store/slices/storage/fileUtils/getUniqueFilename.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.ts
  src/app/store/slices/storage/fileUtils/processDuplicateFiles.ts
  src/app/store/slices/storage/folderUtils/checkFolderDuplicated.test.ts
  src/app/store/slices/storage/folderUtils/checkFolderDuplicated.ts
  src/app/store/slices/storage/folderUtils/getUniqueFolderName.test.ts
  src/app/store/slices/storage/folderUtils/getUniqueFolderName.ts
  src/app/store/slices/storage/folderUtils/renameFolderIfNeeded.test.ts
  src/app/store/slices/storage/folderUtils/renameFolderIfNeeded.ts
  src/app/store/slices/storage/storage.thunks/moveItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/renameItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/storage/types.ts
  src/app/tasks/services/tasks.service/index.ts
  src/use_cases/trash/move-items-to-trash.ts
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1294 [PB-2978]: fix/disallow folder uploads in shared
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/sharedViewUtils.test.ts
  src/app/share/views/SharedLinksView/sharedViewUtils.ts
Labels: bug, ready-for-preview

#1297 [PB-920]: feat/Submit forms when "Enter" is pressed
  .eslintrc.json
  src/app/newSettings/Sections/Account/Account/components/AccountDetailsModal.tsx
  src/app/newSettings/Sections/Account/Security/components/ChangePasswordModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationDisableModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationEnableModal.tsx
  src/app/share/components/SharePasswordInputDialog/SharePasswordInputDialog.tsx
Labels: ready-for-preview

#1296 [PB-2987]: fix/rename item issues in Shared Section
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/share/views/SharedLinksView/hooks/useSharedContextMenu.ts
Labels: bug, ready-for-preview

#1298 [PB-3000/BR-563]: fix/unable to scroll down when restarting account
  src/app/auth/views/RecoverAccountView/RecoverAccountView.tsx
Labels: bug, ready-for-preview

#1302 [_]: fix/notify the user that the tax id is invalid
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, ready-for-preview

#1293 [PB-2391] Feat: users remove themselves from workspace
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/components/LeaveModal.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
Labels: enhancement, ready-for-preview

#1303 [_]: feat/renewal label for subscriptions with coupon code
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/components/checkout/CheckoutProductCard.tsx
  src/app/payment/components/checkout/CheckoutUserAuth.tsx
  src/app/payment/components/checkout/OptionalB2BDropdown.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
Labels: enhancement, ready-for-preview

#1284 [PB-2376]: feat/load Backups incrementally (pagination)
  jest.config.js
  package.json
  src/app/backups/components/BackupList/BackupList.tsx
  src/app/backups/components/BackupList/BackupListItem.tsx
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersList.tsx
  src/app/backups/components/DeviceList/DeviceList.tsx
  src/app/backups/hooks/useBackupDeviceActions.ts
  src/app/backups/hooks/useBackupListActions.ts
  src/app/backups/hooks/useBackupsPagination.test.ts
  src/app/backups/hooks/useBackupsPagination.ts
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/services/new-storage.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/Skeleton/index.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
  src/app/shared/components/List/ListItem.tsx
  src/app/shared/components/List/index.tsx
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  test/unit/services/keys.service.test.ts
  test/unit/services/pgp.service.test.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1311 [_]: fix/initial names for the avatar when the name is null
  src/app/core/components/Navbar/AccountPopover.tsx
  src/app/core/layouts/ShareLayout/ShareLayout.tsx
  src/app/drive/views/MobileView/MobileView.tsx
  src/app/newSettings/Sections/Account/Account/components/UserHeader.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/shared/components/DefaultAvatar/index.tsx
Labels: bug, ready-for-preview

#1304 [PB-2439]:chore/[Technical debt] - Unify login and signup
  jest.config.js
  package.json
  src/__mocks__/WebWorker.ts
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/payment/services/auth-checkout.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  yarn.lock
Labels: ready-for-preview

#1312 [PB-2385]:feat/Refactor url navigation in workspaces
  src/App.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/services/navigation.service.ts
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
  src/app/store/slices/session/session.thunks/index.ts
Labels: ready-for-preview

#1315 [PB-2024]:chore/Find way to export tailwind config
  package.json
  tailwind.config.js
  yarn.lock
Labels: ready-for-preview

#1316 [PB-3037]: fix/update react-pdf worker and destroy the worker after the thumbnail is generated
  src/App.tsx
  src/app/drive/services/thumbnail.service.ts
Labels: bug, enhancement, ready-for-preview

#1318 [_]: fix/react pdf worker
  src/App.tsx
Labels: bug, ready-for-preview

#1319 [_]: fix/breadcrumbs for workspace
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
Labels: bug, ready-for-preview

#765 [PB-516, PB-3058]: feat/send private key encrypted to server wip
  src/app/auth/services/auth.service.ts
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersList.tsx
  src/app/drive/components/DriveListItemSkeleton/DriveListItemSkeleton.tsx
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
Labels: enhancement, needs-sdk-new-version, ready-for-preview

#1323 [PB-2385]:fix/Refactor url navigation in workspaces
  src/app/core/services/navigation.service.ts
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/store/slices/session/session.thunks/index.ts
  src/app/store/slices/workspaces/workspacesStore.ts
Labels: ready-for-preview

#1325 [PB-614]:chore/[Web] Update Tailwind to latest version
  package.json
  yarn.lock
Labels: ready-for-preview

#1327 [_]: refactor/remove unused tracks
  public/index.html
  src/App.tsx
  src/app/analytics/Analytics.ts
  src/app/analytics/services/analytics.service.ts
  src/app/analytics/utils.ts
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/RestartAccount/RestartAccount.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.tsx
  src/app/auth/services/auth.service.ts
  src/app/auth/views/Auth/signup.ts
  src/app/auth/views/BlockedAccountView/BlockedAccountView.tsx
  src/app/core/services/navigation.service.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/components/ShowInvitationsDialog/ShowInvitationsDialog.tsx
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/file.service/index.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/folder.service/index.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/network/UploadManager.ts
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
  src/app/payment/services/auth-checkout.service.ts
  src/app/payment/views/CheckoutCancelView/CheckoutCancelView.tsx
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/store/slices/payment/index.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/utils/backupKeyUtils.ts
  src/react-app-env.d.ts
Labels: enhancement, ready-for-preview

#1322 [MKT-462]: update/Adding halloween theme
  .gitignore
  .vscode/settings.json
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkHalloweenCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/Ghosties-bg.webp
  src/assets/images/banner/web.svg
  yarn.lock
Labels: enhancement, ready-for-preview

#1329 fix missing folder when logout
  src/app/core/services/navigation.service.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
Labels: ready-for-preview

#1330 [_]: fix/keep-referral-tracks
  public/index.html
  src/app/analytics/impact.service.ts
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/payment/services/auth-checkout.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/react-app-env.d.ts
Labels: bug, ready-for-preview

#1328 [_]: fix/remove the spaceLimit param when inviting a member to a workspace
  package.json
  src/app/auth/services/auth.service.ts
  src/app/banners/BannerManager.ts
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  yarn.lock
Labels: bug, ready-for-preview

#1321 [PB-2345]: feat/the owner can modify the assigned space to a given user
  package.json
  src/App.tsx
  src/app/contexts/dialog-manager/ActionDialogManager.context.tsx
  src/app/contexts/dialog-manager/useActionDialog.test.tsx
  src/app/contexts/dialog-manager/useActionDialog.ts
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ModifyStorageModal.tsx
  src/app/newSettings/Sections/Workspace/Members/components/UserCard.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/index.tsx
  yarn.lock
Labels: enhancement, ready-for-preview
