Repository internxt/drive-web, pull requests merged in 2024-12, with the labels that each got.

#1376 [PB-241]: fix/folder upload can't be cancelled
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
Labels: bug, ready-for-preview

#1378 Fix security alerts
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/core/services/navigation.service.ts
  src/app/core/views/RedirectToAppView/RedirectToAppView.tsx
Labels: ready-for-preview

#1382 [MKT_475]: feat/ christmas campaign 2024
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkChristmasCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/christmas_theme.webp
Labels: enhancement, ready-for-preview

#1383 [_]: fix/translations for Log out button in the checkout and removed unused code related to tracks
  src/app/analytics/impact.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/components/checkout/CheckoutUserAuth.tsx
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, enhancement, ready-for-preview

#1389 [_]: fix/appsumo redirects
  src/app/core/config/views.ts
  src/app/routes/hooks/Login/useLoginRedirections.tsx
Labels: bug, ready-for-preview

#1391 [_]: fix/features Banner for dark mode
  src/app/banners/FeaturesBanner.tsx
Labels: enhancement, ready-for-preview

#1390 [_]: release/2.8.1
  package.json
  src/App.tsx
  src/app/analytics/impact.service.ts
  src/app/core/config/views.ts
  src/app/core/services/socket.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/i18n/provider/TranslationProvider.tsx
  src/app/i18n/types.ts
  src/app/newSettings/Sections/Workspace/Billing/BillingDetailsCard.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/UpdateMembersCard.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/ConfirmUpdatedMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/SelectNewMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/containers/BillingWorkspaceOverview.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/components/DetailsInput.tsx
  src/app/newSettings/utils/suscriptionUtils.ts
  src/app/payment/components/checkout/CheckoutUserAuth.tsx
  src/app/payment/services/payment.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/referrals/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/ui/index.ts
  src/app/survey/components/SurveyDialog/SurveyDialog.tsx
  yarn.lock
Labels: bug, enhancement, dependencies, ready-for-preview

#1387 Fix/sync download files
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingBlobs.ts
  src/app/drive/services/download.service/fetchFileBlob.ts
  src/app/drive/services/folder.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
Labels: ready-for-preview

#1395 [PB-3441]: fix/add validation for maximum assignable space
  src/app/newSettings/Sections/Workspace/Members/components/ModifyStorageModal.tsx
Labels: ready-for-preview

#1394 [PB-3306]: feat/disable "Add payment method" for free users
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/components/BillingPaymentMethodCard.tsx
Labels: bug, ready-for-preview

#1399 [_]: fix/remove feedback step when cancelling sub
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Account/Billing/components/CancelSubscription.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
Labels: enhancement, ready-for-preview

#1400 feat: return private key in deep link
  src/app/auth/views/UnivesalLinkSuccessView/UniversalLinkSuccessView.tsx
Labels: ready-for-preview

#1393 [PB-3257]: feat/access logs
  package.json
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/services/auth.service.ts
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Workspace/Logs/AccessLogsSection.tsx
  src/app/newSettings/Sections/Workspace/Logs/components/AccessLogsFilterOptions.tsx
  src/app/newSettings/Sections/Workspace/Logs/hooks/useAccessLogs.test.ts
  src/app/newSettings/Sections/Workspace/Logs/hooks/useAccessLogs.ts
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/newSettings/utils/LogsUtils.ts
  src/app/shared/tables/LoadingSkeleton.tsx
  src/app/shared/tables/ScrollableTable.tsx
  src/app/store/slices/user/index.ts
  yarn.lock
Labels: enhancement, ready-for-preview
