Repository internxt/drive-web, pull requests merged in 2024-05, with the labels that each got.

#1108 Added workspaces calls
  package.json
  src/app/core/factory/sdk/index.ts
  src/app/core/services/workspace.service.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1101 [MKT-315]: feat/star wars campaign
  package.json
  src/app/auth/services/auth.service.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/banners/components/icons/Keyhole.tsx
  src/app/core/services/local-storage.service.ts
  src/app/core/views/Preferences/index.tsx
  src/app/core/views/Preferences/tabs/Account/Appearance.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/payment/services/payment.service.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/star-wars-bg.webp
  yarn.lock
Labels: enhancement, ready-for-preview

#1112 [PB-2080] bugfix/Error uploading files within subfolders of shared folders
  package.json
  src/app/auth/services/auth.service.ts
  src/app/auth/views/Auth/SignupBlog.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/banners/components/icons/Keyhole.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/config/views.ts
  src/app/core/services/local-storage.service.ts
  src/app/core/views/Preferences/index.tsx
  src/app/core/views/Preferences/tabs/Account/Appearance.tsx
  src/app/core/views/Preferences/tabs/Account/Usage.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/payment/services/payment.service.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/Internxt-secure-cloud-storage.webp
  src/assets/images/banner/internxt_secure_cloud_storage.webp
  src/assets/images/banner/star-wars-bg.webp
  yarn.lock
Labels: bug, ready-for-preview

#1111 [PB-1863] feture/Add logic and endpoints to switch between workspaces
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/store/index.ts
  src/app/store/slices/workspaces/workspacesStore.ts
Labels: enhancement, ready-for-preview

#1113 [_]: release/Staging
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/utils/fileViewerWrapperUtils.ts
  src/app/drive/services/database.service.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/storage/index.ts
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1116 [PB-2095] bugfix/Shared items with password not displaying correctly
  package.json
  src/app/core/services/http.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
Labels: bug, ready-for-preview

#1117 [PB-2028] feature/Plans section corrections
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/core/views/Preferences/tabs/Billing/CurrentPlanExtended.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
Labels: bug, enhancement, ready-for-preview

#1115 [PB-2082] feature/Invite user flow
  package.json
  src/App.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/SignUp/CreateAccountForm.tsx
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.tsx
  src/app/auth/utils.ts
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/core/config/views.ts
  src/app/core/services/workspace.service.ts
  src/app/core/types.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/routes/Workspaces/WorkspacesRedirection.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  src/app/routes/paths.json
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/shared/components/forms/BaseCheckbox/BaseCheckbox.tsx
  src/app/store/slices/workspaces/workspacesStore.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1118 [_] release/Staging
  src/app/core/services/http.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/share/views/ShareView/ShareItemPwdView.tsx
Labels: bug, ready-for-preview

#1120 [PB-1442]: feature/Update web frontend (file size limit, items shared)
  package.json
  src/App.tsx
  src/app/core/services/http.service.ts
  src/app/drive/components/SizeLimitDialog/FileSizeLimitDialog.tsx
  src/app/drive/components/SizeLimitDialog/FileSizeLimitDialogContainer.tsx
  src/app/drive/services/new-storage.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/shared/components/Modal/ActionModal.tsx
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/ui/index.ts
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1121 [PB-2028]: feature/Added correct card plan management and translations
  src/app/i18n/locales/de.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
Labels: enhancement, ready-for-preview

#1122 [PB-2100] feature/handle 402 errors
  package.json
  src/App.tsx
  src/app/core/services/error.service.ts
  src/app/core/services/http.service.ts
  src/app/core/types.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/LimitDialogs/FileSizeLimitDialog.tsx
  src/app/drive/components/LimitDialogs/FileSizeLimitDialogContainer.tsx
  src/app/drive/components/LimitDialogs/ShareItemsLimitDialog.tsx
  src/app/drive/components/LimitDialogs/ShareItemsLimitDialogContainer.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/store/index.ts
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/ui/index.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1124 [_]: fix/star wars wallpaper for lifetime plans
  src/app/core/views/Preferences/tabs/Account/Appearance.tsx
  src/app/payment/utils/checkStarWarsCode.ts
Labels: enhancement, ready-for-preview

#1123 [PB-2101] feature/connect workspace members section
  package.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/containers/AccountUsageContainer.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/newSettings/components/Usage/Usage.tsx
  src/app/newSettings/components/Usage/UsageBar.tsx
  src/app/newSettings/containers/UsageContainer.tsx
  src/app/newSettings/utils/membersUtils.ts
  yarn.lock
Labels: ready-for-preview

#1128 [PB-2132] bugfix/On Web, if I drag & drop various folders, only one is uploaded
  package.json
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/drive/services/worker.service/uploadWorkerUtils.ts
  src/app/network/UploadManager.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/store/slices/storage/hooks/useReduxActions.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
Labels: bug, ready-for-preview

#1126 [_]: feat/add-heic-to-the-allowed-previews-list
  package.json
  src/app/core/views/Preferences/tabs/Account/Appearance.tsx
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/components/NoPreviewIsAvailableComponent.tsx
  src/app/drive/components/FileViewer/utils/fileViewerUtils.ts
  src/app/drive/components/FileViewer/viewers/FileImageViewer/FileImageViewer.tsx
  src/app/drive/components/FileViewer/viewers/FileVideoViewer/FileVideoViewer.tsx
  src/app/drive/types/file-types.ts
  src/app/payment/utils/checkStarWarsCode.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1130 [PB-2185]: feat/preview heic images
  package.json
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/components/NoPreviewIsAvailableComponent.tsx
  src/app/drive/components/FileViewer/utils/fileViewerUtils.ts
  src/app/drive/components/FileViewer/viewers/FileImageViewer/FileImageViewer.tsx
  src/app/drive/components/FileViewer/viewers/FileVideoViewer/FileVideoViewer.tsx
  src/app/drive/types/file-types.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1125 [PB-2143]: advanced folder sharing invite via email is broken
  src/app/core/services/http.service.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
Labels: bug, ready-for-preview

#1131 [_]: Release/drive web 2.5.0
  package.json
  src/app/core/services/http.service.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/components/NoPreviewIsAvailableComponent.tsx
  src/app/drive/components/FileViewer/utils/fileViewerUtils.ts
  src/app/drive/components/FileViewer/viewers/FileImageViewer/FileImageViewer.tsx
  src/app/drive/components/FileViewer/viewers/FileVideoViewer/FileVideoViewer.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/types/file-types.ts
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1129 [_]: feat/lifetime banner
  src/app/banners/BannerWrapper.tsx
Labels: enhancement, ready-for-preview

#1132 [_]: fix/file viewer for Shared Links
  src/app/drive/components/FileViewer/FileViewer.tsx
Labels: bug, ready-for-preview

#1133 [PB-2193]: bugfix/Added domain rotation to public shared links and removed redirections
  package.json
  src/App.tsx
  src/app/banners/BannerWrapper.tsx
  src/app/core/services/http.service.ts
  src/app/drive/components/FileViewer/FileViewer.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/share/services/share.service.ts
Labels: bug, ready-for-preview

#1134 [_] feature/Remove api url from code
  src/app/analytics/services/analytics.service.ts
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/backups/services/backups.service.ts
  src/app/core/factory/sdk/index.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/folder.service/index.ts
  src/app/drive/services/plan.service.ts
  src/app/guests/components/GuestDialog/GuestDialog.tsx
  src/app/guests/views/GuestAcceptInviteView/GuestAcceptInviteView.tsx
  src/app/newsletter/services/newsletterService.ts
  src/app/payment/components/token/PayForm.tsx
  src/app/payment/services/payment.service.ts
  src/app/teams/services/teams.service.ts
  src/app/teams/views/DeactivationTeamsView/DeactivationTeamsView.tsx
  src/app/teams/views/JoinTeamView/JoinTeamView.tsx
Labels: enhancement, ready-for-preview

#1138 [PB-2198] feature/Set up playwright
  .github/workflows/playwright.yml
  .gitignore
  package.json
  playwright.config.ts
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1136 [_]: fix/error when purchasing a lifetime plan
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
Labels: bug, ready-for-preview
