Repository internxt/drive-web, pull requests merged in 2024-06, with the labels that each got.

#1141 [_]: fix/restore-old-sharing-path-rotation
  src/app/routes/paths.json
Labels: ready-for-preview

#1140 [BR-188]: fix/update file preview metadata
  src/App.tsx
  src/app/core/plugins/sentry.plugin.ts
  src/app/core/services/navigation.service.ts
  src/app/core/views/Preferences/tabs/Plans/PlanSelector.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/FileViewer/utils/fileViewerWrapperUtils.ts
  src/app/drive/components/FileViewer/viewers/FileImageViewer/FileImageViewer.tsx
  src/app/drive/views/DriveView/DriveView.tsx
Labels: bug, ready-for-preview

#1142 [_]: bugfix/Resolved duplicate route ids
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/routes/paths.json
Labels: bug, enhancement, ready-for-preview

#1146 [MKT-342]: feat/soft sale banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1147 [_]: hotfix/drive banner
  src/app/analytics/utils.ts
  src/app/banners/BannerWrapper.tsx
Labels: bug, ready-for-preview

#1137 [PB-2137] bugfix/ Fixed corrupted zips in brave browser
  .github/workflows/cd-to-share.yml
  .github/workflows/playwright.yml
  .gitignore
  infrastructure/share/share.Dockerfile
  package.json
  playwright.config.ts
  src/app/core/services/zip.service.ts
  src/app/core/services/zipFolder.service.ts
  src/app/drive/services/database.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/folder.service/index.ts
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
  yarn.lock
Labels: bug, ready-for-preview

#1148 [MKT-343]: feat/euro banner
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/assets/images/banner/grass.webp
Labels: enhancement, ready-for-preview

#1153 [PB-2251] feature/Obtain token when expire
  package.json
  src/app/auth/services/user.service.ts
  src/app/core/views/Preferences/index.tsx
  src/app/core/views/Preferences/tabs/Account/AccountDetails.tsx
  src/app/core/views/Preferences/tabs/Account/index.tsx
  src/app/core/views/Preferences/tabs/Security/index.tsx
  src/app/store/slices/user/index.ts
  src/app/store/utils.test.ts
  src/app/store/utils.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1154 [_]: fix/banner
  src/app/analytics/utils.ts
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
Labels: bug, ready-for-preview

#1152 [_] release 2.5
  package.json
  src/app/analytics/services/analytics.service.ts
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/auth/services/user.service.ts
  src/app/backups/services/backups.service.ts
  src/app/core/factory/sdk/index.ts
  src/app/core/services/zip.service.ts
  src/app/core/services/zipFolder.service.ts
  src/app/core/views/ChangeEmailView/index.tsx
  src/app/core/views/Preferences/index.tsx
  src/app/core/views/Preferences/tabs/Account/AccountDetails.tsx
  src/app/core/views/Preferences/tabs/Account/index.tsx
  src/app/core/views/Preferences/tabs/Security/index.tsx
  src/app/drive/services/database.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/folder.service/index.ts
  src/app/drive/services/plan.service.ts
  src/app/guests/components/GuestDialog/GuestDialog.tsx
  src/app/guests/views/GuestAcceptInviteView/GuestAcceptInviteView.tsx
  src/app/newsletter/services/newsletterService.ts
  src/app/payment/components/token/PayForm.tsx
  src/app/payment/services/payment.service.ts
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/store/slices/user/index.ts
  src/app/store/utils.test.ts
  src/app/store/utils.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useRetry.ts
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  src/app/teams/services/teams.service.ts
  src/app/teams/views/DeactivationTeamsView/DeactivationTeamsView.tsx
  src/app/teams/views/JoinTeamView/JoinTeamView.tsx
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1158 [_]: feat/free user promo banner
  src/app/banners/BannerManager.ts
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/assets/images/banner/BannerInternal-SummerCampaign-800x450-EN.svg
  src/assets/images/banner/Crowdcube_Internxt.svg
  src/assets/images/banner/banner_internal_cs_month_800x450_bg.webp
  src/assets/images/banner/christmas_banner_bg.png
  src/assets/images/banner/free-users-banner-bg.webp
  src/assets/images/banner/hearts.png
Labels: enhancement, ready-for-preview

#1159 [_]: feat/update Spanish banner
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/es.json
Labels: enhancement, ready-for-preview

#1160 [PB-218] bugfix/Added dark mode to universal link success view
  src/app/auth/views/UnivesalLinkSuccessView/UniversalLinkSuccessView.tsx
Labels: bug, ready-for-preview

#1162 [_]: feat/speed-up-zip-downloads
  package.json
  src/app/core/services/zip.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadSharedFolderUsingBlobs.ts
  src/app/drive/services/download.service/downloadFolder/downloadSharedFolderUsingFileSystemAPI.ts
  src/app/drive/services/download.service/downloadFolder/downloadSharedFolderUsingReadableStream.ts
  src/app/drive/services/download.service/downloadFolder/downloadSharedFolderUsingStreamSaver.ts
  src/app/drive/services/filesZip.service.ts
  src/app/drive/services/folder.service.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1165 [_]: refactor/remove-legacy-code
  .env.example
  .github/workflows/cd-to-share.yml
  .github/workflows/cd-to-staging.yml
  .github/workflows/ci.yml
  public/index.html
  src/App.tsx
  src/app/core/factory/sdk/index.ts
  src/app/core/services/zipFolder.service.ts
  src/app/core/types.ts
  src/app/database/services/database.service/LRUPhotosCacheManager.ts
  src/app/database/services/database.service/LRUPhotosPreviewCacheManager.ts
  src/app/database/services/database.service/index.ts
  src/app/database/services/database.service/indexed-db.service.ts
  src/app/database/services/database.service/mocks.ts
  src/app/drive/services/database.service.test.ts
  src/app/drive/services/database.service.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/network/download.ts
  src/app/photos/components/PhotoThumbnail.tsx
  src/app/photos/components/Preview.tsx
  src/app/photos/components/ShareDialog.tsx
  src/app/photos/components/Skeleton.tsx
  src/app/photos/components/Toolbar.tsx
  src/app/photos/views/PhotosView.tsx
  src/app/routes/paths.json
  src/app/share/views/ShareView/SharePhotosView.tsx
  src/app/store/index.ts
  src/app/store/slices/photos/index.ts
  src/app/store/slices/photos/thunks/delete.ts
  src/app/store/slices/photos/thunks/download.ts
  src/app/store/slices/photos/thunks/fetch.ts
  src/app/store/slices/photos/thunks/index.ts
  src/app/tasks/services/tasks.service/index.ts
  src/app/tasks/types.ts
  src/react-app-env.d.ts
  test/e2e/cypress.json
  test/e2e/cypress/integration/photos.spec.ts
  test/e2e/cypress/utils/photos.mock.ts
Labels: enhancement, ready-for-preview

#1161 [PB-2183, PB-2203] feature/List and upload files and folders to B2B workspace
  package.json
  src/App.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/core/services/local-storage.service.ts
  src/app/core/services/workspace.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemDragAndDrop.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/services/file.service/index.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/new-storage.service.ts
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/network/UploadManager.ts
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/store/slices/session/session.thunks/index.ts
  src/app/store/slices/storage/storage.selectors.ts
  src/app/store/slices/storage/storage.thunks/createFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchSortedFolderContentThunk.ts
  src/app/store/slices/storage/storage.thunks/goToFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/renameItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/workspaces/workspaces.selectors.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1170 [_]: feature/Updated sdk and drive folder type
  package.json
  src/app/drive/types/index.ts
  yarn.lock
Labels: enhancement, ready-for-preview
