Repository internxt/drive-web, pull requests merged in 2024-09, with the labels that each got.

#1249 [MKT-439]: feat/back to work banner
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1250 [PB-2715] fix/check de translation
  src/app/i18n/locales/de.json
Labels: ready-for-preview

#1252 [_]: fix/one time payments using coupons with 100% OFF
  package.json
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  yarn.lock
Labels: bug, ready-for-preview

#1253 [PB-2663] bugfix/Restoring files from the trash is broken
  src/app/store/slices/storage/index.ts
Labels: ready-for-preview

#1256 [PB-2772]: bugfix/ Downloads keeps downloading when cancelled
  src/app/drive/services/folder.service.ts
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
Labels: bug, ready-for-preview

#1247 [MKT-427]: feat/integrated checkout for b2b (UI)
  src/app/core/types.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/components/checkout/OptionalB2BDropdownComponent.tsx
  src/app/payment/components/checkout/ProductCardComponent.tsx
  src/app/payment/components/checkout/SelectSeatsComponent.tsx
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/store/checkoutReducer.ts
  src/app/payment/store/types.ts
  src/app/payment/types.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/hooks/checkout/useCheckout.ts
Labels: enhancement, ready-for-preview

#1258 [PB-2691]: feat/remove obsolete teams section
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/core/config/views.ts
  src/app/core/factory/sdk/index.ts
  src/app/core/layouts/HeaderAndSidenavLayout/HeaderAndSidenavLayout.tsx
  src/app/core/services/local-storage.service.ts
  src/app/core/types.ts
  src/app/guests/components/GuestDialog/GuestDialog.tsx
  src/app/payment/components/ProductItem/ProductItem.scss
  src/app/payment/components/ProductItem/ProductItem.tsx
  src/app/routes/paths.json
  src/app/store/index.ts
  src/app/store/slices/plan/index.ts
  src/app/store/slices/storage/storage.selectors.ts
  src/app/store/slices/team/index.ts
  src/app/store/slices/ui/index.ts
  src/app/store/slices/user/index.ts
  src/app/teams/components/InviteTeamMemberDialog/InviteTeamMemberDialog.tsx
  src/app/teams/services/teams.service.ts
  src/app/teams/types.ts
  src/app/teams/views/DeactivationTeamsView/DeactivationTeamsView.tsx
  src/app/teams/views/JoinTeamView/JoinTeamView.tsx
  src/app/teams/views/TeamSuccessView/TeamSuccessView.tsx
  src/index.tsx
Labels: ready-for-preview

#1260 [PB-2703] bugfix/Prevent show empty cards of workspace billing data
  package.json
  src/app/drive/services/file.service/uploadFile.ts
  src/app/newSettings/Sections/Workspace/Billing/containers/BillingWorkspaceOverview.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  yarn.lock
Labels: bug, ready-for-preview

#1261 [PB-2458]: fix/display right-click menu
  src/app/shared/components/List/ListItem.tsx
Labels: ready-for-preview

#1259 [MKT-450]: feat/soft sale campaign
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1264 fix: remove firefox and brave download as stream exceptions
  package.json
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/folder.service.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
Labels: enhancement, ready-for-preview

#1150 [IN-57]: feature/migrate drive web to cloudflare
  .github/workflows/cd-cloudflare.yml
Labels: enhancement, ready-for-preview

#1277 [_]: fix/int checkout payment button
  src/app/payment/services/checkout.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, ready-for-preview

#1281 [_]: refactor/remove unused payment code
  src/App.tsx
  src/app/auth/views/Auth/signup.ts
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/api/plansApi.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/RedirectToCheckoutView/CheckoutPlanView.tsx
  src/app/routes/paths.json
Labels: enhancement, ready-for-preview

#1280 [BR-489]: fix/DE Web restore files from trash text surpasses box width
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/i18n/locales/de.json
Labels: bug, enhancement, ready-for-preview

#1279 [BR-490]: feat/order by size not working
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/store/slices/storage/storage.thunks/fetchSortedFolderContentThunk.ts
Labels: bug, ready-for-preview

#1278 [PB-2867]: feat/loading state for pricing section - Settings
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/InfoCardComponent.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/PlanSelectionCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/PlanSelectionComponent.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/skeletons/InfoPlanCardSkeleton.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/skeletons/PlanSelectionCardSkeleton.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/newSettings/components/Invoices/InvoicesList.tsx
  src/app/newSettings/utils/suscriptionUtils.ts
  src/app/payment/services/currency.service.ts
Labels: enhancement, ready-for-preview

#1283 [_]: bugfix/navigating between folders with size sort selected
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
Labels: enhancement, ready-for-preview

#1285 [_]: fix/file viewer navigation for backups
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
Labels: bug, ready-for-preview

#1265 [PB-469]: fix/breadcrumbs and New folder dialog name issues
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveStoreProps.tsx
  src/app/drive/components/EditFolderNameDialog/EditFolderNameDialog.tsx
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/store/slices/ui/index.ts
Labels: bug, ready-for-preview

#1288 [_]: fix/empty trash description
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/containers/AccountUsageContainer.tsx
Labels: bug
