Repository internxt/drive-web, pull requests merged in 2024-07, with the labels that each got.

#1167 [PB-2220,PB-2221] feature/Worskpaces trash
  package.json
  src/app/core/factory/sdk/index.ts
  src/app/core/services/local-storage.service.ts
  src/app/core/services/workspace.service.ts
  src/app/drive/components/ClearTrashDialog/ClearTrashDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/drive/views/TrashView/TrashView.tsx
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Account/AccountSection.tsx
  src/app/store/slices/workspaces/workspacesStore.ts
  src/use_cases/trash/clear-trash.ts
  src/use_cases/trash/delete-items.ts
  src/use_cases/trash/get_trash.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1172 [PB-2082] feature/invite user flow
  package.json
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.tsx
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/core/services/workspace.service.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/UserCard.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/InviteDialogContainer.tsx
  src/app/routes/hooks/Login/useLoginRedirections.tsx
  yarn.lock
Labels: ready-for-preview

#1173 [PB-2293]: feature/Enable downloading of Worskpaces items in Drive
  src/app/analytics/services/analytics.service.ts
  src/app/core/services/local-storage.service.ts
  src/app/core/services/workspace.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingBlobs.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingStreamSaver.ts
  src/app/drive/services/download.service/fetchFileBlob.ts
  src/app/drive/services/download.service/fetchFileStream.ts
  src/app/drive/services/download.service/index.ts
  src/app/drive/services/file.service/index.ts
  src/app/drive/services/filesZip.service.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/folder.service/index.ts
  src/app/drive/services/foldersZip.service.ts
  src/app/drive/services/network.service/index.ts
  src/app/drive/services/thumbnail.service.ts
  src/app/drive/types/index.ts
  src/app/network/download.ts
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/updateItemMetadataThunk.ts
Labels: enhancement, ready-for-preview

#1174 [MKT-394]: feat/summer campaign
  src/app/auth/views/Auth/SignupBlog.tsx
  src/app/banners/BannerManager.ts
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1177 [PB-2133] feature/workspace members
  src/app/core/services/workspace.service.ts
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  src/app/newSettings/components/Usage/UsageBar.tsx
  src/app/newSettings/utils/membersUtils.ts
Labels: ready-for-preview

#1163 [PB-2222] feat: update sections Plans/Billings
  package.json
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/banners/BannerManager.ts
  src/app/core/components/Navbar/AccountPopover.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/core/services/workspace.service.ts
  src/app/drive/components/ClearTrashDialog/ClearTrashDialog.tsx
  src/app/drive/components/DeleteItemsDialog/DeleteItemsDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/PlanUsage/PlanUsage.tsx
  src/app/drive/components/WarningMessage/WarningMessageWrapper.tsx
  src/app/drive/services/limit.service.ts
  src/app/drive/services/plan.service.ts
  src/app/drive/types/index.ts
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Account/containers/DeleteAccountContainer.tsx
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Account/Billing/components/CancelSubscription.tsx
  src/app/newSettings/Sections/Account/Billing/containers/BillingAccountOverview.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/api/plansApi.ts
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/containers/BillingWorkspaceOverview.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/components/BillingPaymentMethodCard.tsx
  src/app/newSettings/components/Invoices/InvoicesList.tsx
  src/app/newSettings/containers/InvoicesContainer.tsx
  src/app/newSettings/hooks/useDefaultPaymentMethod.tsx
  src/app/newSettings/utils/suscriptionUtils.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
  src/app/store/slices/plan/index.ts
  src/app/store/slices/referrals/index.ts
  src/app/store/slices/storage/storage.thunks/deleteItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/workspaces/workspaces.selectors.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1176 [BR-220, PB-2319] bugfix/web lang.en-us on language dropdown
  src/app/newSettings/Sections/General/components/Language.tsx
Labels: bug, ready-for-preview

#1178 [PB-2302] feature/Add new sdk call to enable Firefox folder download
  package.json
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingBlobs.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingStreamSaver.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/new-storage.service.ts
  src/app/drive/types/index.ts
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1183 [PB-2321] fix/border color on name collision dialog options
  src/app/drive/components/NameCollisionDialog/index.tsx
Labels: ready-for-preview

#1182 [_] fix/workspace testing
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
Labels: ready-for-preview

#1181 [PB-2305, PB-2342] feature/Hide B2B feature in production environment, fix download and upload items
  package.json
  src/App.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelectorContainer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/DriveExplorer/utils.ts
  src/app/drive/services/network.service/index.ts
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/fetchDialogContentThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/store/slices/workspaces/workspaces.selectors.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  src/use_cases/trash/delete-items.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1184 Changed workspace usage endpoint
  package.json
  src/app/core/services/workspace.service.ts
  src/app/store/slices/plan/index.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1185 [PB-2346- PB-2350] feature/prevent workspace being created more than one
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersList.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
Labels: enhancement, ready-for-preview

#1187 [PB 2348]: Update free plan to 1Gb and add per user in business plans
  src/app/drive/types/index.ts
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
  src/app/store/slices/plan/index.ts
Labels: ready-for-preview

#1188 [_]: Removed unnecessary billing data and fixed plan card button display
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/types/types.tsx
Labels: bug, ready-for-preview

#1186 [PB-2341] feature/workspaces url navigation
  src/App.tsx
  src/app/core/components/Navbar/AccountPopover.tsx
  src/app/core/components/Navbar/NavbarGlobalSearch.tsx
  src/app/core/services/navigation.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Account/containers/AccountUsageContainer.tsx
  src/app/newSettings/Sections/Account/Billing/containers/BillingAccountOverview.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/newSettings/types/types.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useOpen.tsx
Labels: ready-for-preview

#1189 [PB-2341] feature/workspaces url navigationv
  src/app/drive/views/DriveView/DriveView.tsx
Labels: ready-for-preview

#1190 [PB-2351] feature/Adde user text and translations in business plans
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelectionCard.tsx
Labels: enhancement

#1193 [PB-2220, PB-1541]: bugfix/edit workspace details and undo moved items to trash
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/store/slices/storage/storage.thunks/moveItemsThunk.ts
  src/use_cases/trash/move-items-to-trash.ts
Labels: bug, ready-for-preview

#1191 [_] : feature/add reactivate member flow
  package.json
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/components/ReactivateModal.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1194 [PB-2341] workspaces url navigation
  src/app/drive/views/DriveView/DriveView.tsx
Labels: ready-for-preview

#1195 [_]: fix/redeem codes from website
  src/app/auth/components/SignUp/SignUp.tsx
Labels: bug, ready-for-preview

#1196 [PB-2220] fix/move to trash
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
Labels: ready-for-preview

#1197 [PB-239] fix/personal invitations appear in workspace
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/SidenavItem/SidenavItem.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/share/views/SharedLinksView/components/TopBarButtons.tsx
Labels: ready-for-preview

#1198 [_]: Minor adjustments
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ReactivateModal.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
Labels: enhancement, ready-for-preview

#1199 [PB-2353] Feat: Workspace Billing - Fix Billing Details and Payment Method information
  package.json
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/components/BillingPaymentMethodCard.tsx
  src/app/newSettings/hooks/useDefaultPaymentMethod.tsx
  src/app/store/slices/workspaces/workspacesStore.ts
  yarn.lock
Labels: ready-for-preview

#1200 [_]: feature/Added international phone library
  package.json
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1202 [MKT-378]: feat/update country API
  src/app/newSettings/Sections/Account/Plans/api/plansApi.ts
Labels: bug, ready-for-preview

#1201 [MKT-378]: fix/country API
  src/app/core/views/Preferences/tabs/Plans/PlanSelector.tsx
Labels: enhancement, ready-for-preview

#1175 [BR-220, PB-2319] : bugfix/web lang.en-us on language dropdown
  src/app/core/views/Preferences/tabs/Account/Language.tsx
Labels: bug, ready-for-preview

#1204 [PB-2398] bugfix/Navigate inside workspace shared subfolders
  package.json
  src/app/core/services/workspace.service.ts
  src/app/newSettings/Sections/General/components/Language.tsx
  src/app/share/views/SharedLinksView/hooks/useFetchSharedData.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1206 [_] bugfix/Fix setup workspace after purchasing a b2b plan
  src/app/store/slices/workspaces/workspacesStore.ts
Labels: enhancement, ready-for-preview

#1205 [PB-2398] Bugfix/add resources token to shared items upload and download
  package.json
  src/app/core/services/workspace.service.ts
  src/app/drive/services/file.service/uploadFile.ts
  src/app/drive/services/new-storage.service.ts
  src/app/network/UploadManager.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  yarn.lock
Labels: ready-for-preview

#1208 [_]: feature/Unhide b2b options
  src/App.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
Labels: enhancement, ready-for-preview

#1209 [BR-251] bugfix/Display correct billing information in workspace overview section
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
Labels: bug, ready-for-preview

#1210 [BR-249] bugfix/Error setting up root folder uuid in invitation sign up
  package.json
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  yarn.lock
Labels: bug, ready-for-preview

#1212 [PB-2419] bugfix/Member can't rename shared file
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/storage/index.ts
Labels: bug, ready-for-preview

#1214 [PB-2426] bugfix/User can't upload a 20GB file to drive
  src/app/drive/components/ReachedPlanLimitDialog/ReachedPlanLimitDialog.tsx
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
Labels: bug, ready-for-preview

#1213 [PB-2418] Upgrade now" button below space gauge doesn't redirect correctly
  src/app/drive/components/PlanUsage/PlanUsage.tsx
Labels: bug, ready-for-preview

#1215 [_] bugfix/add new preferences modal navigation
  src/app/drive/components/WarningMessage/WarningMessage.tsx
  src/app/drive/components/WarningMessage/WarningMessageWrapper.tsx
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
  src/app/store/slices/referrals/index.ts
Labels: bug, ready-for-preview
