Repository internxt/drive-web, pull requests merged in 2024-08, with the labels that each got.

#1217 [PB-2414] bugfix/Fix workspaces first version bugs
  src/app/drive/components/PlanUsage/PlanUsage.tsx
  src/app/drive/components/ReachedPlanLimitDialog/ReachedPlanLimitDialog.tsx
  src/app/drive/components/WarningMessage/WarningMessage.tsx
  src/app/drive/components/WarningMessage/WarningMessageWrapper.tsx
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/store/slices/referrals/index.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
Labels: bug, ready-for-preview

#1218 [PB-2372] manage teams
  package.json
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/TeamsSection.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/AddMemberDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/CreateTeamDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/TeamDetails.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/TeamsList.tsx
  src/app/newSettings/containers/SectionListContainer.tsx
  src/app/newSettings/utils/membersUtils.ts
  src/app/shared/components/Input/index.tsx
  tailwind.config.js
  yarn.lock
Labels: ready-for-preview

#1211 [MKT-305]: feat/integrated checkout
  package.json
  src/App.tsx
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/backups/components/DeviceList/DeviceList.tsx
  src/app/core/config/views.ts
  src/app/core/layouts/ShareLayout/ShareLayout.tsx
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/i18n/provider/TranslationProvider.tsx
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/payment/components/ProductItem/ProductItem.tsx
  src/app/payment/components/checkout/Header.tsx
  src/app/payment/components/checkout/InputsComponent.tsx
  src/app/payment/components/checkout/ProductCardComponent.tsx
  src/app/payment/components/checkout/UserAuthComponent.tsx
  src/app/payment/components/paymentBridges/INXT.tsx
  src/app/payment/components/paymentBridges/PayPal.tsx
  src/app/payment/services/auth-checkout.service.ts
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/money.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/store/checkoutReducer.ts
  src/app/payment/store/types.ts
  src/app/payment/types.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/CheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/payment/views/RedirectToCheckoutView/CheckoutPlanView.tsx
  src/app/routes/paths.json
  src/app/share/components/ShareItemDialog/components/TextInput.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Button/Button.tsx
  src/app/theme/ThemeProvider.tsx
  src/assets/icons/checkout/guarantee-dark.svg
  src/assets/icons/checkout/guarantee-white.svg
  src/hooks/checkout/useCheckout.ts
  src/hooks/useDebounce.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1222 [_]: fix/small bugs related to error display and upsell button in integrated checkout
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/components/checkout/InputsComponent.tsx
  src/app/payment/components/checkout/ProductCardComponent.tsx
  src/app/payment/components/checkout/UserAuthComponent.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, ready-for-preview

#1223 [_]: Added param to buy b2b plan from website redirection
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/views/RedirectToCheckoutView/CheckoutPlanView.tsx
Labels: bug, ready-for-preview

#1225 [_] : bugfix/Fix impact analytics in integrated checkout
  package.json
  src/app/analytics/services/analytics.service.ts
  src/app/core/services/workspace.service.ts
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  yarn.lock
Labels: bug, ready-for-preview

#1226 [_] feature/Add custom payment id for lifetimes of integrated checkout
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1227 [_]: feature/Add payment intent id in lifetime plans
  package.json
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1228 [PB-2513] fix/clear workspace on logout
  src/app/store/slices/user/index.ts
  src/app/store/slices/workspaces/workspacesStore.ts
Labels: ready-for-preview

#1224 [PB-2437] feature/Allow update b2b plan
  package.json
  src/app/core/services/workspace.service.ts
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/CheckoutView/CheckoutPlanView.tsx
  src/app/store/slices/storage/storage.thunks/updateItemMetadataThunk.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1203 [_] feature/add loader while switching workspace
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/store/slices/workspaces/workspacesStore.ts
Labels: ready-for-preview

#1221 [PB-2372] feature/manage teams
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Teams/TeamsSection.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/ChangeManagerDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/DeleteTeamDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/RemoveTeamMemberDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/TeamDetails.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/TeamsList.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/AddMemberDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/ChangeManagerDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/CreateTeamDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/DeleteTeamDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/RemoveTeamMemberDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/RenameTeamDialogContainer.tsx
  src/app/newSettings/Sections/Workspace/Teams/containers/TeamDetailsContainer.tsx
Labels: ready-for-preview

#1231 [PB-2523] feature/Remove ui and logic from referral program
  src/app/auth/components/InviteAFriendWidget/InviteAFriendWidget.tsx
  src/app/auth/services/user.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/AccountSection.tsx
  src/app/newSettings/Sections/Account/Account/containers/InviteFriendSectionContainer.tsx
  src/app/newSettings/Sections/Account/Account/containers/InvitedFriendsContainer.tsx
  src/app/newSettings/hooks/useInviteFriends.ts
Labels: enhancement, ready-for-preview

#1235 [PB-2401] feature/increase upload file size
  src/app/drive/services/network.service/index.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: ready-for-preview

#1232 [PB-2399 ,PB-2468]: feature/Increase files to upload at once to 3000
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/UploadItemsFailsDialog/UploadItemsFailsDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/BaseDialog/BaseDialog.tsx
Labels: enhancement, ready-for-preview

#1239 [MKT-424]: feat/updating subscription if needed from integrated checkout
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1237 [PB-2392] Feat: owner can remove members from workspace
  package.json
  src/app/core/services/workspace.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Members/components/RemoveModal.tsx
  src/app/newSettings/Sections/Workspace/Members/containers/MemberDetailsContainer.tsx
  yarn.lock
Labels: ready-for-preview

#1240 [PB-2372] fix/manage teams
  src/app/drive/views/DriveView/DriveView.tsx
  src/app/newSettings/Sections/Workspace/Teams/TeamsSection.tsx
  src/app/routes/hooks/Drive/useDrive.tsx
Labels: ready-for-preview

#1241 [PB-2596] fix/sorting not working
  src/app/store/slices/storage/storage.thunks/fetchFolderContentThunk.ts
Labels: ready-for-preview

#1244 [PB-2612] [PB-2614] fix/names and downloads in backups
  package.json
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersList.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
  src/app/store/slices/backups/index.ts
  yarn.lock
Labels: ready-for-preview

#1245 [MKT-434]: fix/avoid activating/deactivating upsells from auth toggle button and fix saved discount
  src/app/payment/components/checkout/ProductCardComponent.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
Labels: bug, ready-for-preview

#1248 [_] fix/removed old teams calls with mnemonic
  src/app/store/slices/user/index.ts
  src/app/teams/components/InviteTeamMemberDialog/InviteTeamMemberDialog.tsx
  src/app/teams/services/teams.service.ts
  src/app/teams/views/TeamSuccessView/TeamSuccessView.tsx
Labels: ready-for-preview
