Repository internxt/drive-web, pull requests merged in 2025-06, with the labels that each got.

#1547 [_]:feat/ Add Bitdefender PopUp Banner
  src/app/analytics/impact.service.test.ts
  src/app/banners/BannerManager.test.ts
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/BitDefenderBanner.tsx
  src/app/payment/utils/checkStarWarsCode.test.ts
  src/assets/images/banner/Ban_Internext.jpg
Labels: enhancement, ready-for-preview

#1549 [PB-4511]: tests/impact service coverage
  CODEOWNERS
  src/app/analytics/impact.service.test.ts
  src/app/analytics/impact.service.ts
  src/app/core/services/env.service.node.test.ts
Labels: enhancement, ready-for-preview

#1544 [MKT-533]: feat/Enviroment day campaign
  src/app/banners/FeaturesBanner.tsx
  src/app/core/services/local-storage.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkEnvironmentCode.test.ts
  src/app/payment/utils/checkEnvironmentCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/environment_theme.png
  src/assets/images/banner/shield-blue.svg
Labels: ready-for-preview

#1552 [_]: feat/ Replace BitDefenderBanner with FeaturesBanner and update offer end date
  src/app/banners/BannerWrapper.tsx
Labels: enhancement, ready-for-preview

#1550 [PB-4136]: feat/migrate from CRA to Vite
  .github/workflows/playwright.yml
  README.md
  craco.config.js
  index.html
  package.json
  postcss.config.js
  src/app/auth/components/AuthSideInfo/AuthSideInfo.tsx
  src/app/auth/components/SignUp/CreateAccountForm.tsx
  src/app/auth/views/BlockedAccountView/BlockedAccountView.tsx
  src/app/auth/views/RecoverAccountView/RecoverAccountView.tsx
  src/app/auth/views/RecoveryLinkView/RecoveryLinkView.tsx
  src/app/auth/views/SignInView/SignInView.tsx
  src/app/auth/views/SignUpView/SignUpView.tsx
  src/app/auth/views/UnivesalLinkSuccessView/UniversalLinkSuccessView.tsx
  src/app/banners/BitDefenderBanner.tsx
  src/app/banners/CyberAwarenessBanner.tsx
  src/app/banners/SummerBanner.tsx
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/layouts/ShareLayout/ShareLayout.tsx
  src/app/core/services/env.service.node.test.ts
  src/app/core/services/env.service.ts
  src/app/core/services/error.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveItemContextMenu.tsx
  src/app/drive/components/DriveExplorer/DriveTopBarItems.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/services/icon.service.ts
  src/app/drive/views/FolderFileNotFound/FolderFileNotFound.tsx
  src/app/drive/views/MobileView/MobileView.tsx
  src/app/drive/views/RequestAccess/RequestAccess.tsx
  src/app/i18n/services/i18n.service.ts
  src/app/payment/components/checkout/CheckoutProductCard.tsx
  src/app/payment/components/checkout/Header.tsx
  src/app/payment/utils/checkManagementIdCode.test.ts
  src/app/payment/utils/checkStarWarsCode.test.ts
  src/app/share/views/ShareView/SendBanner.tsx
  src/app/share/views/ShareView/ShareItemPwdView.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/shared/views/ExpiredLink/ExpiredLinkView.tsx
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskToRetryItem/TaskToRetryItem.tsx
  src/assets/fonts/InstrumentSans/InstrumentSans-variable.woff2
  src/assets/fonts/InstrumentSans/font.css
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  vitest.config.ts
  vitest.shared.ts
  vitest.workspace.ts
  yarn.lock
Labels: enhancement, dependencies, ready-for-preview

#1551 [_]: feat/Integrate Google Sheets API for logging offline conversions
  .env.example
  src/app/analytics/googleSheet.service.test.ts
  src/app/analytics/googleSheet.service.ts
  src/app/analytics/impact.service.ts
  src/app/core/services/env.service.ts
  src/app/core/services/local-storage.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1567 [_]: fix/dashlane-pqc-kybe-wasm-not-found
  package.json
  vite.config.mts
  yarn.lock
Labels: ready-for-preview

#1568 [_] feature/Remove unused jszip dependency and dead code
  package.json
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingBlobs.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingFileSystemAccessAPI.ts
  src/app/drive/services/download.service/downloadFolder/downloadFolderUsingStreamSaver.ts
  src/app/drive/services/download.service/downloadFolder/index.ts
  src/app/drive/services/download.service/index.ts
  yarn.lock
Labels: enhancement, dependencies, ready-for-preview

#1564 [_]: Update Sentry dependencies
  package.json
  src/app/core/plugins/sentry.plugin.ts
  src/app/core/services/error.service.ts
  yarn.lock
Labels: dependencies, ready-for-preview

#1577 [_]: bugfix/Control null name values in avatar component
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/Sections/Workspace/Overview/components/WorkspaceAvatarWrapper.tsx
Labels: bug, ready-for-preview

#1582 [_] Add passToHash test
  test/unit/services/utils.passToHash.test.ts
Labels: ready-for-preview

#1581 [PB-4554] fix limit test, remove notification mock
  src/app/backups/hooks/useBackupsPagination.test.ts
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/constants.ts
  src/app/drive/hooks/trash/useTrashPagination.test.ts
  src/app/drive/services/limit.service.test.ts
  src/app/drive/services/limit.service.ts
  src/app/network/DownloadManager.test.ts
  src/app/share/services/share.service.test.ts
  src/app/shared/components/CurrentPlan/index.tsx
  src/app/store/slices/sharedLinks/index.test.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.test.ts
Labels: ready-for-preview

#1553 [PB-4509]: fix/search bar is highlighted when creating account
  src/app/payment/utils/checkEnvironmentCode.test.ts
  src/app/payment/utils/checkStarWarsCode.test.ts
  src/app/shared/components/Tutorial/Tutorial.tsx
Labels: bug, ready-for-preview

#1580 [_]: refactor/user themes redemption
  CODEOWNERS
  package.json
  src/app/core/services/local-storage.service.test.ts
  src/app/core/services/local-storage.service.ts
  src/app/core/services/storage-keys.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/services/payment.service.ts
  src/app/payment/utils/checkChristmasCode.ts
  src/app/payment/utils/checkEnvironmentCode.test.ts
  src/app/payment/utils/checkEnvironmentCode.ts
  src/app/payment/utils/checkHalloweenCode.ts
  src/app/payment/utils/checkManagementIdCode.test.ts
  src/app/payment/utils/checkManagementIdCode.ts
  src/app/payment/utils/checkStPatrciksCode.ts
  src/app/payment/utils/checkStarWarsCode.test.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/utils/checkSuperBowlCode.test.ts
  src/app/payment/utils/checkSuperBowlCode.ts
  src/app/theme/ThemeProvider.tsx
  src/app/theme/userThemes.service.test.ts
  src/app/theme/userThemes.service.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#1586 [_] Fix Buffer error when pbkdf2 is updated
  vitest.shared.ts
Labels: ready-for-preview

#1588 [PB-4571] bugfix/'Modify storage' bar is not working on Workspaces
  src/app/newSettings/Sections/Workspace/Members/components/ModifyStorageModal.tsx
Labels: bug, ready-for-preview

#1585 [_]: feat/release 2.10.0
  CODEOWNERS
  package.json
  src/app/analytics/googleSheet.service.ts
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/user.service.ts
  src/app/backups/services/backups.service.test.ts
  src/app/backups/services/backups.service.ts
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/factory/sdk/index.ts
  src/app/core/services/local-storage.service.test.ts
  src/app/core/services/local-storage.service.ts
  src/app/core/services/storage-keys.ts
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/services/file.service/index.test.ts
  src/app/drive/services/new-storage.service.test.ts
  src/app/drive/services/usage.service.test.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/AccountSection.tsx
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/services/checkout.service.test.ts
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/services/products.service.ts
  src/app/payment/utils/checkChristmasCode.ts
  src/app/payment/utils/checkEnvironmentCode.test.ts
  src/app/payment/utils/checkEnvironmentCode.ts
  src/app/payment/utils/checkHalloweenCode.ts
  src/app/payment/utils/checkManagementIdCode.test.ts
  src/app/payment/utils/checkManagementIdCode.ts
  src/app/payment/utils/checkStPatrciksCode.ts
  src/app/payment/utils/checkStarWarsCode.test.ts
  src/app/payment/utils/checkStarWarsCode.ts
  src/app/payment/utils/checkSuperBowlCode.test.ts
  src/app/payment/utils/checkSuperBowlCode.ts
  src/app/referrals/services/users-referrals.service.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Tutorial/Tutorial.tsx
  src/app/store/slices/user/index.ts
  src/app/theme/ThemeProvider.tsx
  src/app/theme/userThemes.service.test.ts
  src/app/theme/userThemes.service.ts
  test/e2e/tests/helper/staticData.ts
  test/e2e/tests/pages/loginPage.ts
  test/unit/services/utils.passToHash.test.ts
  vite.config.mts
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1589 [_]: fix/remove-temp-avatar-URL
  src/app/auth/services/user.service.ts
  src/app/core/factory/sdk/index.ts
  src/app/core/services/env.service.node.test.ts
  src/app/core/services/env.service.ts
Labels: ready-for-preview
