Repository internxt/drive-web, pull requests merged in 2025-03, with the labels that each got.

#1483 change plan cards
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/InfoCardComponent.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/PlanSelectionCard.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanSelection/PlanSelectionComponent.tsx
  src/app/payment/components/checkout/CheckoutProductCard.tsx
Labels: ready-for-preview

#1484 [_]: fix/pc cloud flow
  src/app/core/config/views.ts
  src/app/core/types.ts
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/CheckoutSuccessView/PcCloudSuccess.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/routes/paths.json
Labels: enhancement, ready-for-preview

#1486 [_]: feat/Show space in the checkout for users of pc components
  src/app/payment/components/checkout/CheckoutProductCard.tsx
Labels: enhancement, ready-for-preview

#1489 [MKT_502]: feat/SpringCampaign
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/banners/SubscriptionBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/assets/images/banner/internxt_vpn_antivirus_new_plans.webp
Labels: ready-for-preview

#1233 [PB-985]: feature/playwright e2e tests
  .github/workflows/playwright.yml
  package.json
  playwright.config.ts
  src/app/auth/services/auth.service.ts
  src/app/banners/BannerManager.ts
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  test/e2e/tests/example.spec.ts
  test/e2e/tests/global.d.ts
  test/e2e/tests/global.ts
  test/e2e/tests/helper/staticData.ts
  test/e2e/tests/pages/drivePage.ts
  test/e2e/tests/pages/loginPage.ts
  test/e2e/tests/pages/recoveryPasswordPage.ts
  test/e2e/tests/pages/signUpPage.ts
  test/e2e/tests/specs/DRIVE-internxt-folder-creation-deletion.spec.ts
  test/e2e/tests/specs/DRIVE-internxt-folder-file-deletion.spec.ts
  test/e2e/tests/specs/internxt-login.spec.ts
  test/e2e/tests/specs/internxt-signup.spec.ts
  test/e2e/tests/specs/login.setup.ts
  test/e2e/tests/specs/playwright/auth/credentials.json
  test/e2e/tests/specs/playwright/auth/user.json
  test/e2e/tests/uploads/ingles folder data.xlsx
  yarn.lock
Labels: stalled, ready-for-preview

#1490 [MKT_503]: update/condition to show banners
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
Labels: ready-for-preview

#1494 [_]: feat/upgrade UI for lifetime users
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/drive/components/PlanUsage/PlanUsage.tsx
  src/app/drive/services/limit.service.ts
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/newSettings/Sections/Account/Plans/utils/planUtils.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
  src/app/shared/components/CurrentPlan/index.tsx
Labels: enhancement, ready-for-preview

#1497 [_]: feat/match subscription and lifetime by product id instead
  package.json
  src/app/newSettings/Sections/Account/Plans/PlansSection.tsx
  yarn.lock
Labels: enhancement, ready-for-preview

#1498 fix: fit edit payment method popup
  src/app/newSettings/Sections/Workspace/Billing/components/EditPaymentMethodForm.tsx
Labels: bug, ready-for-preview

#1499 [MKT_506]: feat/StPatricks Campaign
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkStPatrciksCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/StPatrick-bg.png
Labels: enhancement, ready-for-preview

#1500 [MKT_506]: fix/StPatricks web app theme
  src/app/payment/utils/checkStPatrciksCode.ts
Labels: ready-for-preview

#1495 [PB-4063]: Feat/logs the user out of the VPN
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/services/auth.service.ts
  src/app/auth/services/vpnAuth.service.test.ts
  src/app/auth/services/vpnAuth.service.ts
  src/hooks/useVpnAuth.test.ts
  src/hooks/useVpnAuth.ts
Labels: enhancement, ready-for-preview

#1466 [PB-3511]:Chore/Add modal
  package.json
  src/app/core/components/Sidenav/PendingInvitationsDialog.tsx
  src/app/drive/components/ClearTrashDialog/ClearTrashDialog.tsx
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/DeleteItemsDialog/DeleteItemsDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/drive/components/MoveItemsDialog/MoveItemsDialog.tsx
  src/app/drive/components/NameCollisionDialog/index.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareUserNotRegistered/ShareUserNotRegistered.tsx
  src/app/drive/components/ShareWithTeamDialog/ShareWithTeamDialog.tsx
  src/app/drive/components/ShowInvitationsDialog/ShowInvitationsDialog.tsx
  src/app/drive/components/StopSharingAndMoveToTrashDialogWrapper/components/StopSharingAndMoveToTrashDialog/index.tsx
  src/app/drive/components/StopSharingItemDialog/StopSharingItemDialog.tsx
  src/app/newSettings/PreferencesDialog.tsx
  src/app/newSettings/Sections/Account/Account/components/AccountDetailsModal.tsx
  src/app/newSettings/Sections/Account/Account/components/ChangeEmailModal.tsx
  src/app/newSettings/Sections/Account/Account/components/UploadAvatarModal.tsx
  src/app/newSettings/Sections/Account/Account/containers/DeleteAccountContainer.tsx
  src/app/newSettings/Sections/Account/Plans/components/ChangePlanDialog.tsx
  src/app/newSettings/Sections/Account/Security/components/ChangePasswordModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationDisableModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationEnableModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditBillingDetailsModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/EditPaymentMethodModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/ConfirmUpdatedMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Billing/components/UpdateMembers/SelectNewMembersModal.tsx
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ActionModal.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ModifyStorageModal.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/Sections/Workspace/Overview/components/UploadAvatarModal.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/AddMemberDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/ChangeManagerDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/CreateTeamDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/DeleteTeamDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/RemoveTeamMemberDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/RenameTeamDialog.tsx
  src/app/share/components/SharePasswordDisableDialog/SharePasswordDisableDialog.tsx
  src/app/share/components/SharePasswordInputDialog/SharePasswordInputDialog.tsx
  src/app/shared/components/Modal/index.tsx
  yarn.lock
Labels: ready-for-preview

#1469 [PB-3516]:chore/Add dialog from UI
  src/app/auth/components/DeleteAccountDialog/DeleteAccountDialog.tsx
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/drive/components/DeleteBackupDialog/DeleteBackupDialog.tsx
  src/app/share/views/SharedLinksView/SharedView.tsx
  src/app/shared/components/Dialog/Dialog.tsx
  test/e2e/tests/pages/loginPage.ts
Labels: ready-for-preview

#1470 [PB-3526]:chore/Add checkbox
  package.json
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/components/ActivityFilters.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/AddMemberDialog.tsx
  src/app/shared/components/Grid/GridItem.tsx
  src/app/shared/components/Grid/index.tsx
  src/app/shared/components/forms/BaseCheckbox/BaseCheckbox.tsx
  src/app/shared/components/forms/BaseCheckbox/BaseCheckboxOld.tsx
  src/app/shared/components/forms/BaseCheckbox/Check.svg
  src/app/shared/components/forms/BaseCheckbox/Minus.svg
  yarn.lock
Labels: ready-for-preview

#1471 [PB-3525]:chore/ add input
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/RecoveryLink/RecoveryLink.tsx
  src/app/auth/components/RestartAccount/RestartAccount.tsx
  src/app/core/views/ChangeEmailView/index.tsx
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/components/AccountDetailsModal.tsx
  src/app/newSettings/Sections/Account/Account/components/ChangeEmailModal.tsx
  src/app/newSettings/Sections/Account/Security/components/ChangePasswordModal.tsx
  src/app/newSettings/Sections/Account/Security/components/EnterPassword.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationDisableModal.tsx
  src/app/newSettings/Sections/Account/Security/components/TwoFactorAuthenticationEnableModal.tsx
  src/app/newSettings/Sections/Workspace/Logs/components/AccessLogsFilterOptions.tsx
  src/app/newSettings/Sections/Workspace/Members/InviteDialog.tsx
  src/app/newSettings/Sections/Workspace/Members/MembersSection.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/AddMemberDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/CreateTeamDialog.tsx
  src/app/newSettings/Sections/Workspace/Teams/components/RenameTeamDialog.tsx
  src/app/newSettings/components/DetailsInput.tsx
  src/app/share/components/SharePasswordInputDialog/SharePasswordInputDialog.tsx
  src/app/shared/components/Input/index.tsx
  src/app/shared/components/ValidPassword/index.tsx
Labels: ready-for-preview

#1487 [PB-3757]:fix/popover item
  src/app/core/components/Navbar/AccountPopover.tsx
Labels: ready-for-preview

#1501 [_]: feature/Added PR Size Checker action
  .github/workflows/pr-size-control.yml
Labels: enhancement, ready-for-preview

#1492 [PB-3238]: feat/improve-download-speeds
  src/app/backups/views/BackupsView/BackupsView.tsx
  src/app/core/services/zip.service.ts
  src/app/database/services/database.service/LRUFilesCacheManager.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemActions.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/DriveExplorer/components/DriveTopBarActions.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/services/downloadManager.service.test.ts
  src/app/drive/services/downloadManager.service.ts
  src/app/drive/services/folder.service.ts
  src/app/drive/services/foldersZip.service.ts
  src/app/network/DownloadManager.test.ts
  src/app/network/DownloadManager.ts
  src/app/network/UploadFolderManager.test.ts
  src/app/network/UploadFolderManager.ts
  src/app/share/services/share.service.test.ts
  src/app/share/services/share.service.ts
  src/app/share/types/index.ts
  src/app/share/views/SharedLinksView/containers/SharedItemListContainer.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/store/slices/storage/folderUtils/createFolder.test.ts
  src/app/store/slices/storage/hooks/useReduxActions.test.ts
  src/app/store/slices/storage/hooks/useReduxActions.ts
  src/app/store/slices/storage/storage.thunks/downloadFileThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/downloadItemsThunk.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/hooks/useRetry.ts
  src/app/utils/queueUtils.ts
  src/app/utils/timeUtils.test.ts
  src/app/utils/timeUtils.ts
Labels: ready-for-preview

#1504 [_]: fix/close-zip-public-shares
  src/app/drive/services/folder.service.ts
Labels: ready-for-preview

#1506 [MKT_512]: feat/ world-cloud-security-campaign
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.module.scss
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: ready-for-preview
