Repository internxt/drive-web, pull requests merged in 2025-04, with the labels that each got.

#1511 [PB-4187] feature/Enhance task logger indicator to display current progress and completed files
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
Labels: enhancement, ready-for-preview

#1480 [PB-3707]: fix/copy-shared-link
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/share/components/ShareItemDialog/ShareItemDialog.tsx
  src/app/share/services/share.service.ts
  src/app/shared/components/Copyable/index.tsx
Labels: ready-for-preview

#1513 [MKT_513]: feat/ ID Management Campaign (April 8-18)
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkManagementIdCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/IdManagement-bg.png
Labels: ready-for-preview

#1516 [_]: fix/Change light mode featuresBanner design and display logic
  src/app/banners/BannerManager.ts
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
Labels: ready-for-preview

#1518 [PB-3882]: fix/profile picture breaks on drive
  src/app/auth/services/user.service.ts
  src/app/newSettings/Sections/Account/Account/components/AvatarWrapper.tsx
  src/app/newSettings/Sections/Workspace/Overview/components/WorkspaceAvatarWrapper.tsx
  src/app/store/slices/user/index.ts
  src/app/utils/avatar/avatarUtils.test.ts
  src/app/utils/avatar/avatarUtils.ts
Labels: bug, ready-for-preview

#1519 [PB-3870]: fix/failed decryption of backups names
  src/app/backups/services/backups.service.ts
  src/app/backups/utils/mappers.test.ts
  src/app/backups/utils/mappers.ts
Labels: bug, ready-for-preview
