Repository internxt/drive-web, pull requests merged in 2025-08, with the labels that each got.

#1620 [MKT_542]: feat/5th anniversary campaign
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/core/services/storage-keys.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/theme/ThemeProvider.tsx
  src/app/theme/userThemes.service.ts
  src/assets/images/banner/5th_anniversary_theme.avif
Labels: ready-for-preview

#1623 [MKT_542]:fix/height for features banner
  src/app/banners/FeaturesBanner.tsx
Labels: bug, ready-for-preview

#1625 [_]: feat/remove-d-path-segment
  src/App.tsx
  src/app/share/services/share.service.ts
Labels: ready-for-preview

#1538 [PB-4382]: feat/shorten-public-share-links
  src/app/share/services/share.service.test.ts
  src/app/share/services/share.service.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/utils/stringUtils.test.ts
  src/app/utils/stringUtils.ts
Labels: enhancement, ready-for-preview

#1629 [_]: fix/handle setup intent for subs and fix useless redirects for coupons
  src/app/payment/hooks/useUserPayment.test.ts
  src/app/payment/hooks/useUserPayment.ts
  src/app/payment/types.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, ready-for-preview

#1601 [PB-4498] feature/Modify invite users to shared item flow
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/user.service.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/store/slices/sharedLinks/index.test.ts
  src/app/store/slices/sharedLinks/index.ts
Labels: enhancement, ready-for-preview

#1617 [_]: feat/GTM AddShoppersTracking
  index.html
  src/app/analytics/addShopper.services.test.ts
  src/app/analytics/addShoppers.services.ts
  src/app/analytics/impact.service.test.ts
  src/app/analytics/impact.service.ts
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/react-app-env.d.ts
Labels: ready-for-preview

#1630 [PB-3669]: feature/logic to create invoices using crypto
  src/app/contexts/dialog-manager/ActionDialogManager.context.tsx
  src/app/payment/hooks/useUserPayment.test.ts
  src/app/payment/hooks/useUserPayment.ts
  src/app/payment/services/checkout.service.ts
  src/app/payment/types.ts
Labels: enhancement, ready-for-preview

#1627 [PB-4764] feature/fix infinite loading when navigate to private shared link
  src/app/share/services/redirections.service.test.ts
  src/app/share/services/redirections.service.ts
  src/app/share/views/SharedLinksView/SharedView.tsx
Labels: bug, ready-for-preview

#1599 [PB-4600] Remove patch from download
  src/app/core/services/zip.service.ts
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/downloadManager.service.test.ts
  src/app/network/download.ts
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/react-app-env.d.ts
Labels: ready-for-preview

#1605 [PB-4671] Optimize encryption of big files
  src/app/core/services/stream.service.ts
  src/app/network/NetworkFacade.ts
  src/app/network/UploadManager.ts
  src/app/network/crypto.test.ts
  src/app/network/crypto.ts
  src/app/network/networkConstants.ts
  src/app/network/upload.ts
Labels: enhancement, ready-for-preview

#1638 [PB-4702]: feat/add klarna as allowed payment method
  src/app/payment/services/checkout.service.test.ts
  src/app/payment/services/checkout.service.ts
Labels: enhancement, ready-for-preview

#1639 [PB-4614]: fix/hide rename option in root shared folder
  src/app/drive/services/downloadManager.service.test.ts
  src/app/share/views/SharedLinksView/hooks/useSharedContextMenu.ts
Labels: bug, ready-for-preview
