Repository internxt/drive-web, pull requests merged in 2025-01, with the labels that each got.

#1398 add hybrid encryption funcions
  src/app/crypto/services/pgp.service.ts
  src/app/crypto/services/utils.ts
  test/unit/services/pgp.service.test.ts
  test/unit/services/utils.hash.test.ts
Labels: ready-for-preview

#1407 [_]: fix/check if image is valid before creating thumbnails
  src/app/drive/services/network.service/index.ts
  src/app/drive/services/thumbnail.service.ts
Labels: bug, ready-for-preview

#1397 Add kyber keys only
  package.json
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/crypto/services/keys.service.ts
  src/app/crypto/services/pgp.service.ts
  src/app/crypto/services/utils.ts
  test/unit/services/keys.service.test.ts
  test/unit/services/pgp.service.test.ts
  test/unit/services/utils.hash.test.ts
  yarn.lock
Labels: ready-for-preview

#1409 [_]: chore/exclude tsx and js files from sonar scan
  sonar-project.properties
  vitest.config.js
Labels: enhancement, ready-for-preview

#1396 [PB-3502]: fix/unable to drag and drop more than 200 files
  .github/pull_request_template.md
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
  src/app/store/slices/storage/fileUtils/getFilesByBatchs.test.ts
  src/app/store/slices/storage/fileUtils/getFilesByBatchs.ts
  src/app/store/slices/storage/storage.thunks/renameItemsThunk.ts
Labels: bug, ready-for-preview

#1411 [PB-3581]: feat/improve pagination and loading state for access logs
  src/app/newSettings/Sections/Workspace/Logs/AccessLogsSection.tsx
  src/app/shared/tables/LoadingSkeleton.tsx
  src/app/shared/tables/ScrollableTable.tsx
Labels: enhancement, ready-for-preview

#1412 [PB-3596]:Fix/fix mocks in preparefilesToUpload tests
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
Labels: ready-for-preview

#1408 [PB-2666] switch to hybrid dec
  src/app/crypto/services/pgp.service.ts
  src/app/share/services/share.service.test.ts
  src/app/share/services/share.service.ts
  test/unit/services/pgp.service.test.ts
Labels: ready-for-preview

#1414 [BR-888]: feat/use the same date format through the app
  src/app/backups/components/BackupsAsFoldersList/BackupsAsFoldersList.tsx
  src/app/backups/components/DeviceList/DeviceList.tsx
  src/app/core/services/date.service.ts
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/drive/components/ItemDetailsDialog/ItemDetailsDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/share/components/ShareItemDialog/ShareItemDialog.tsx
Labels: enhancement, ready-for-preview

#1415 [PB-3581]: fix/settings dialog larger than the viewport
  src/app/newSettings/PreferencesDialog.tsx
  src/app/shared/tables/ScrollableTable.tsx
Labels: bug, ready-for-preview

#1406 [PB-3585]: fix/get invoices by userType and not by subId
  package.json
  src/app/auth/components/SignUp/useSignUp.test.ts
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Billing/BillingAccountSection.tsx
  src/app/newSettings/Sections/Workspace/Billing/BillingWorkspaceSection.tsx
  src/app/newSettings/components/BillingPaymentMethodCard.tsx
  src/app/newSettings/containers/InvoicesContainer.tsx
  yarn.lock
Labels: bug, ready-for-preview

#1416 [_] remove dead code
  src/app/crypto/services/utilspgp.ts
Labels: ready-for-preview

#1417 Update prepareFilesToUpload tests
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
Labels: ready-for-preview

#1424 [BR-903]: fix/cancel subscription button isn't working for b2b plans
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Workspace/Billing/CancelSubscriptionModal.tsx
Labels: bug, ready-for-preview

#1423 [_]: feat/tracking payment actions
  .env.example
  src/app/analytics/ga.service.ts
  src/app/analytics/impact.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: ready-for-preview

#1401 [PB-471]:fix/Generic messages
  src/app/drive/components/CreateFolderDialog/CreateFolderDialog.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  src/app/drive/components/EditItemNameDialog/EditItemNameDialog.tsx
  src/app/drive/components/FileViewer/FileViewerWrapper.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/components/AccountDetailsModal.tsx
  src/app/notifications/components/NotificationToast/NotificationToast.tsx
  src/app/shared/components/Modal/index.tsx
  src/app/store/slices/sharedLinks/index.ts
  src/app/store/slices/storage/index.ts
  src/app/store/slices/storage/storage.thunks/createFolderThunk.ts
  src/app/store/slices/ui/index.ts
Labels: ready-for-preview

#1427 [_]: fix/Google ads tracking
  src/app/analytics/impact.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1432 [_]: fix/Login to the desktop app
  src/app/auth/services/auth.service.ts
Labels: bug, ready-for-preview

#1434 [_]: feat/ tag path update for handle selected plan
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1421 [PB-3626] Add Kyber keys and functions (but not use in encyption)
  CODEOWNERS
  package.json
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.tsx
  src/app/auth/components/SignUp/useSignUp.test.ts
  src/app/auth/components/SignUp/useSignUp.ts
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/crypto/services/keys.service.ts
  src/app/crypto/services/pgp.service.ts
  src/app/crypto/services/utils.ts
  src/app/share/services/share.service.test.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  test/unit/services/keys.service.test.ts
  test/unit/services/pgp.service.test.ts
  test/unit/services/utils.hash.test.ts
  vitest.config.js
  yarn.lock
Labels: ready-for-preview

#1435 [_]: feat/ changed tags for google ads
  src/app/analytics/impact.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: ready-for-preview

#1437 [_] fix mock error in login test
  src/app/auth/services/auth.service.test.ts
Labels: ready-for-preview

#1425 [PB-3160]: feat/ Migrate credentials and email verification
  package.json
  src/app/auth/services/auth.service.ts
  src/app/auth/services/user.service.ts
  src/app/core/views/ChangeEmailView/index.tsx
  src/app/core/views/VerifyEmailView/index.tsx
  src/app/newSettings/Sections/Account/Account/components/ChangeEmailModal.tsx
  src/app/newSettings/Sections/Account/Security/components/EnterPassword.tsx
  yarn.lock
Labels: ready-for-preview

#1438 [PB-3627]: put checks to avoid errors if user.keys does not exist
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.tsx
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/crypto/services/keys.service.ts
  src/app/share/services/share.service.test.ts
  src/app/share/services/share.service.ts
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
Labels: ready-for-preview

#1420 [PB-3627]: feat/send-kyber-private-key-reencrypted-on-pwd-change-request
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
Labels: ready-for-preview

#1440 [_]: update/Google ads tags value
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: ready-for-preview

#1442 [_]: delete/google ads tracking
  public/index.html
  src/app/analytics/impact.service.ts
  src/app/payment/views/CheckoutSuccessView/CheckoutSuccessView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: ready-for-preview

#1441 [PB-3627]: Update sdk to 1.9.5
  package.json
  yarn.lock
Labels: ready-for-preview

#1428 [PB-3457]: fix/Add UI content to tailwind config
  src/app/drive/components/DriveExplorer/DriveExplorerList/DriveExplorerList.tsx
  tailwind.config.js
Labels: ready-for-preview

#1433 [PB-3651]:fix/unstable grid items movement
  src/app/drive/components/DriveExplorer/DriveExplorerGrid/DriveExplorerGrid.tsx
Labels: ready-for-preview

#1426 [PB-3458]:chore/Integrate breadcrumbs component from UI
  package.json
  src/app/shared/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsItem/BreadcrumbsItem.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuBackups.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsBackupsView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsDriveView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsMoveItemsDialogView.tsx
  src/app/shared/components/Breadcrumbs/Containers/BreadcrumbsSharedView.tsx
  src/app/shared/components/Breadcrumbs/helper.test.ts
  src/app/shared/components/Breadcrumbs/helper.ts
  src/app/shared/components/Breadcrumbs/types.tsx
  yarn.lock
Labels: ready-for-preview

#1444 [PB-3675]:fix/issue search preview
  src/app/core/components/Navbar/FilterItem.tsx
Labels: ready-for-preview

#1446 [_] Chore/add test for workspace guest signup
  .github/workflows/ci.yml
  package.json
  sonar-project.properties
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.test.tsx
  src/app/core/views/DeactivationView/DeactivationView.tsx
  src/app/network/crypto.test.ts
  src/app/network/crypto.ts
  src/setupTests.ts
  vitest.config.js
  yarn.lock
Labels: ready-for-preview

#1443 [MKT_490]: feat/Superbowl campaign
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkSuperBowlCode.ts
  src/app/theme/ThemeProvider.tsx
  src/assets/images/banner/superbowl_theme.webp
Labels: enhancement, ready-for-preview
