Repository internxt/drive-web, pull requests merged in 2025-02, with the labels that each got.

#1452 [PB-3237]: feat/move-upload-folders-to-upload-manager-class
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/network/UploadFolderManager.ts
  src/app/network/UploadFoldersManager.test.ts
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/folderUtils/uploadFolders.ts
Labels: enhancement, ready-for-preview

#1445 [PB-2666] Use hybrid encryption for private file sharing and remove double base64 encoding on kyber private keys
  package.json
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.test.tsx
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/crypto/services/keys.service.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/share/services/share.service.ts
  src/app/store/slices/sharedLinks/index.test.ts
  src/app/store/slices/sharedLinks/index.ts
  yarn.lock
Labels: ready-for-preview

#1447 [_] Chore/add test for share guest signup
  src/app/auth/services/auth.service.test.ts
  src/app/share/views/SharedGuestSignUp/ShareGuestSignUpView.test.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSingUpView.tsx
  src/app/shared/components/Breadcrumbs/helper.test.ts
  test/unit/services/keys.service.test.ts
Labels: ready-for-preview

#1458 [MKT_496]: feat: Valentine's campaign
  src/app/banners/BannerWrapper.tsx
  src/app/banners/FeaturesBanner.tsx
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: enhancement, ready-for-preview

#1460 [_]: update/FeaturesBanner in dark mode
  src/app/banners/FeaturesBanner.tsx
Labels: enhancement, ready-for-preview

#1456 [PB-3717] bugfix/retry upload file
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/network/upload.test.ts
  src/app/network/upload.ts
Labels: ready-for-preview

#1457 [PB-3763]:fix/bump ui version to fix edit profile image
  package.json
  yarn.lock
Labels: ready-for-preview

#1448 Improve resposive desing for small sizes
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/DriveExplorerListItem/DriveExplorerListItem.tsx
  src/app/shared/components/Breadcrumbs/BreadcrumbsMenu/BreadcrumbsMenuDrive.tsx
  tailwind.config.js
Labels: ready-for-preview

#1464 [_]: remove/ twitter tracking
  public/index.html
Labels: ready-for-preview

#1439 [PB-3237]: feat/improve-upload-speeds
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/drive/components/DriveExplorer/DriveExplorerItem/hooks/useDriveItemDragAndDrop.tsx
  src/app/drive/components/NameCollisionDialog/NameCollisionContainer.tsx
  src/app/network/UploadFolderManager.ts
  src/app/network/UploadFoldersManager.test.ts
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.ts
  src/app/store/slices/storage/folderUtils/createFolder.test.ts
  src/app/store/slices/storage/folderUtils/createFolder.ts
  src/app/store/slices/storage/storage.thunks/index.ts
  src/app/store/slices/storage/storage.thunks/uploadFolderThunk.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  vitest.config.js
Labels: ready-for-preview

#1463 store email in lowercase
  src/app/drive/components/DriveExplorer/DriveExplorer.tsx
  src/app/newSettings/Sections/Account/Account/AccountSection.tsx
Labels: ready-for-preview

#1459 [PB-3796]:Chore/newapi avatar profile deactive
  package.json
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/user.service.ts
  src/app/core/views/DeactivationView/DeactivationView.tsx
  yarn.lock
Labels: ready-for-preview

#1467 [PB-3796]:fix/ url avatar api
  src/app/auth/services/user.service.ts
Labels: ready-for-preview

#1468 rollback user avatar
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/user.service.ts
Labels: ready-for-preview

#1472 [_]: update/ remove unnecesary texts on the checkout
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
Labels: ready-for-preview

#1474 [_]: update/new text for companyVatId in checkout
  src/app/i18n/locales/es.json
Labels: enhancement, ready-for-preview

#1477 fix loader downloading button
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
Labels: bug, ready-for-preview

#1453 [PB-3774]: feat/auth for vpn extension
  src/App.tsx
  src/app/auth/components/LogIn/LogIn.tsx
  src/app/auth/components/SignUp/SignUp.tsx
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/auth.service.ts
  src/hooks/useVpnAuth.test.ts
  src/hooks/useVpnAuth.ts
Labels: enhancement, ready-for-preview

#1481 [PB-3943] feature/Added mobile flow for integrated checkout
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/payment/components/checkout/CheckoutProductCard.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutView.tsx
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview

#1482 [PB-3943] feature/Added new enpdoint for mobile trial checkout
  src/app/payment/services/checkout.service.ts
  src/app/payment/services/payment.service.ts
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: enhancement, ready-for-preview
