Repository internxt/drive-web, pull requests merged in 2025-05, with the labels that each got.

#1522 [PB-3967, PB-3968] Feat: add fails files to the queue and allow user downloading later
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/downloadManager.service.test.ts
  src/app/drive/services/downloadManager.service.ts
  src/app/drive/services/folder.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/network/DownloadManager.test.ts
  src/app/network/DownloadManager.ts
  src/app/network/RetryManager.test.ts
  src/app/network/RetryManager.ts
  src/app/network/UploadManager.test.ts
  src/app/network/UploadManager.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.test.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/components/TaskToRetry/TaskToRetry.test.tsx
  src/app/tasks/components/TaskToRetry/TaskToRetry.tsx
  src/app/tasks/components/TaskToRetryItem/TaskToRetryItem.test.tsx
  src/app/tasks/components/TaskToRetryItem/TaskToRetryItem.tsx
Labels: ready-for-preview

#1521 [PB-3966] Feat: Continue downloading the folder even if a file fails
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/downloadManager.service.test.ts
  src/app/drive/services/downloadManager.service.ts
  src/app/drive/services/filesZip.service.test.ts
  src/app/drive/services/filesZip.service.ts
  src/app/drive/services/folder.service.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/network/DownloadManager.test.ts
  src/app/network/DownloadManager.ts
  src/app/network/RetryManager.test.ts
  src/app/network/RetryManager.ts
  src/app/network/UploadManager.test.ts
  src/app/network/UploadManager.ts
  src/app/share/services/share.service.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.test.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
  src/app/tasks/components/TaskLogger/TaskLogger.tsx
  src/app/tasks/components/TaskLoggerActions/TaskButtonActionBlocks.tsx
  src/app/tasks/components/TaskLoggerActions/TaskLoggerActions.tsx
  src/app/tasks/components/TaskLoggerItem/TaskLoggerItem.tsx
  src/app/tasks/components/TaskToRetry/TaskToRetry.test.tsx
  src/app/tasks/components/TaskToRetry/TaskToRetry.tsx
  src/app/tasks/components/TaskToRetryItem/TaskToRetryItem.test.tsx
  src/app/tasks/components/TaskToRetryItem/TaskToRetryItem.tsx
Labels: ready-for-preview

#1535 [_]: fix/handle taxes with promo code in query
  src/app/payment/views/IntegratedCheckoutView/CheckoutViewWrapper.tsx
Labels: bug, ready-for-preview

#1536 [_] : feature/Added location env
  .github/workflows/cd-to-share.yml
Labels: bug, enhancement, ready-for-preview

#1537 [_]: feat/update plan features to match website and improve JSON structure
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Plans/components/PlanCard.tsx
  src/app/payment/components/checkout/CheckoutProductCard.tsx
Labels: enhancement, ready-for-preview

#1520 [_]: hotfix/id management theme and General section
  src/app/core/services/local-storage.service.test.ts
  src/app/core/services/local-storage.service.ts
  src/app/network/DownloadManager.test.ts
  src/app/newSettings/Sections/General/GeneralSection.tsx
  src/app/newSettings/Sections/General/components/Appearance.tsx
  src/app/payment/utils/checkManagementIdCode.test.ts
  src/app/payment/utils/checkManagementIdCode.ts
  src/app/payment/utils/checkStarWarsCode.test.ts
Labels: bug, ready-for-preview
