Repository internxt/drive-web, pull requests merged in 2025-07, with the labels that each got.

#1584 [PB-4495] feature/Obfuscate source code
  package.json
  vite.config.mts
  yarn.lock
Labels: enhancement, dependencies, ready-for-preview

#1595 Revert "[PB-4495] feature/Obfuscate source code"
  package.json
  vite.config.mts
  yarn.lock
Labels: bug, enhancement, ready-for-preview

#1596 [PB-4586] feagure/Ignore hidden files when upload folders
  src/app/network/UploadFolderManager.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.ts
Labels: enhancement, ready-for-preview

#1572 [PB-4554] Add test for workspaceStore
  src/app/analytics/googleSheet.service.test.ts
  src/app/analytics/impact.service.test.ts
  src/app/auth/components/SignUp/WorkspaceGuestSignUp.test.tsx
  src/app/auth/components/SignUp/useSignUp.test.ts
  src/app/auth/services/auth.service.test.ts
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/vpnAuth.service.test.ts
  src/app/backups/hooks/useBackupsPagination.test.ts
  src/app/backups/utils/mappers.test.ts
  src/app/banners/BannerManager.test.ts
  src/app/core/constants.ts
  src/app/core/services/env.service.node.test.ts
  src/app/core/services/http.service.ts
  src/app/core/services/local-storage.service.test.ts
  src/app/drive/components/ShareInviteDialog/ShareInviteDialog.tsx
  src/app/drive/hooks/trash/useTrashPagination.test.ts
  src/app/drive/services/download.service/downloadBackup.ts
  src/app/drive/services/download.service/downloadFile.ts
  src/app/drive/services/downloadManager.service.test.ts
  src/app/drive/services/downloadManager.service.ts
  src/app/drive/services/file.service/index.test.ts
  src/app/drive/services/filesZip.service.test.ts
  src/app/drive/services/foldersZip.service.test.ts
  src/app/drive/services/limit.service.test.ts
  src/app/network/DownloadManager.test.ts
  src/app/network/DownloadManager.ts
  src/app/network/RetryManager.test.ts
  src/app/network/UploadFolderManager.test.ts
  src/app/network/UploadManager.test.ts
  src/app/network/UploadManager.ts
  src/app/network/upload.test.ts
  src/app/newSettings/Sections/Account/Plans/api/plansApi.test.ts
  src/app/newSettings/Sections/Workspace/Logs/hooks/useAccessLogs.test.ts
  src/app/payment/services/checkout.service.test.ts
  src/app/share/services/share.service.test.ts
  src/app/share/views/ShareView/ShareFileView.tsx
  src/app/share/views/ShareView/ShareFolderView.tsx
  src/app/share/views/SharedGuestSignUp/ShareGuestSignUpView.test.tsx
  src/app/shared/components/Breadcrumbs/helper.test.ts
  src/app/store/slices/sharedLinks/index.test.ts
  src/app/store/slices/storage/fileUtils/getUniqueFileName.test.ts
  src/app/store/slices/storage/fileUtils/prepareFilesToUpload.test.ts
  src/app/store/slices/storage/folderUtils/checkFolderDuplicated.test.ts
  src/app/store/slices/storage/folderUtils/createFolder.test.ts
  src/app/store/slices/storage/folderUtils/getUniqueFolderName.test.ts
  src/app/store/slices/storage/hooks/useReduxActions.test.ts
  src/app/store/slices/storage/storage.thunks/uploadItemsThunk.test.ts
  src/app/store/slices/workspaces/workspacesStore.test.ts
  src/app/store/slices/workspaces/workspacesStore.ts
  src/app/tasks/components/TaskToRetry/TaskToRetry.test.tsx
  src/app/theme/userThemes.service.test.ts
  src/app/utils/avatar/avatarUtils.test.ts
  src/app/utils/userLocation.test.ts
  src/hooks/checkout/useCheckout.test.ts
  src/hooks/useVpnAuth.test.ts
  test/unit/services/keys.service.test.ts
Labels: ready-for-preview

#1600 [PB-4238]: fix/add loading state while fetching workspace limit and usage
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/store/slices/plan/index.ts
Labels: bug, ready-for-preview

#1603 [PB-4563]: fix/drive Web B2B workspace not displaying used storage correctly
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/containers/UsageContainer.tsx
Labels: bug, ready-for-preview

#1602 [PB-4483]: fix/"Security" preferences menu closes immediately when "Show Password" (Eye Icon) is clicked
  src/app/newSettings/Sections/Account/Security/components/EnterPassword.tsx
  src/app/share/components/SharePasswordInputDialog/SharePasswordInputDialog.tsx
Labels: bug, ready-for-preview

#1525 [PB-4236] feature/Add recover account new flow with old backup key
  src/app/auth/components/ChangePassword/ChangePassword.tsx
  src/app/auth/services/auth.service.ts
  src/app/utils/backupKeyUtils.test.ts
  src/app/utils/backupKeyUtils.ts
Labels: enhancement, ready-for-preview

#1604 [PB-4381]: feat/use the avatar blob from the local DB or fetch it again
  src/app/auth/services/user.service.test.ts
  src/app/auth/services/user.service.ts
  src/app/core/components/Sidenav/Sidenav.tsx
  src/app/core/components/Sidenav/WorkspaceSelector.tsx
  src/app/drive/components/ShareDialog/ShareDialog.tsx
  src/app/drive/components/ShareDialog/components/InvitedUsersSkeletonLoader.tsx
  src/app/drive/components/ShareDialog/components/User.tsx
  src/app/drive/components/ShareDialog/components/UserOptions.tsx
  src/app/drive/components/ShareDialog/types.ts
  src/app/i18n/locales/de.json
  src/app/i18n/locales/en.json
  src/app/i18n/locales/es.json
  src/app/i18n/locales/fr.json
  src/app/i18n/locales/it.json
  src/app/i18n/locales/ru.json
  src/app/i18n/locales/tw.json
  src/app/i18n/locales/zh.json
  src/app/newSettings/Sections/Account/Account/components/AvatarWrapper.tsx
  src/app/newSettings/Sections/Workspace/Overview/OverviewSection.tsx
  src/app/newSettings/Sections/Workspace/Overview/components/WorkspaceAvatarWrapper.tsx
  src/hooks/useAvatar.test.ts
  src/hooks/useAvatar.tsx
Labels: bug, ready-for-preview

#1610 [_]:feat/Implement Sales Tracking for AddShoppers with WELCOME Code
  src/app/analytics/addShopper.services.test.ts
  src/app/analytics/addShoppers.services.ts
  src/app/analytics/impact.service.test.ts
  src/app/analytics/impact.service.ts
  src/app/auth/services/auth.service.ts
Labels: enhancement, ready-for-preview

#1616 [_] Updated duplicated lines text of readme
  README.md
Labels: enhancement, ready-for-preview
